// Code generated by MockGen. DO NOT EDIT.
// Source: gin-vue-admin/internal/pkg/bifrosts (interfaces: Manager)
//
// Generated by this command:
//
//	mockgen -self_package=gin-vue-admin/internal/pkg/bifrosts -destination mock_bifrosts.go -package bifrosts gin-vue-admin/internal/pkg/bifrosts Manager
//

// Package bifrosts is a generated GoMock package.
package bifrosts

import (
	v1 "github.com/tanganyu1114/heimdallr-reborn/server/api/heimdallr_api/v1"
	v10 "github.com/tanganyu1114/heimdallr-reborn/server/internal/pkg/meta/v1"
	sort_map "github.com/tanganyu1114/heimdallr-reborn/server/pkg/sort_map"
	reflect "reflect"

	v11 "github.com/ClessLi/bifrost/pkg/client/bifrost/v1"
	gomock "go.uber.org/mock/gomock"
)

// MockManager is a mock of Manager interface.
type MockManager struct {
	ctrl     *gomock.Controller
	recorder *MockManagerMockRecorder
	isgomock struct{}
}

// MockManagerMockRecorder is the mock recorder for MockManager.
type MockManagerMockRecorder struct {
	mock *MockManager
}

// NewMockManager creates a new mock instance.
func NewMockManager(ctrl *gomock.Controller) *MockManager {
	mock := &MockManager{ctrl: ctrl}
	mock.recorder = &MockManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockManager) EXPECT() *MockManagerMockRecorder {
	return m.recorder
}

// GetBifrostClient mocks base method.
func (m *MockManager) GetBifrostClient(opts v10.WebServerOptions) (*v11.Client, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBifrostClient", opts)
	ret0, _ := ret[0].(*v11.Client)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBifrostClient indicates an expected call of GetBifrostClient.
func (mr *MockManagerMockRecorder) GetBifrostClient(opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBifrostClient", reflect.TypeOf((*MockManager)(nil).GetBifrostClient), opts)
}

// GetGroup mocks base method.
func (m *MockManager) GetGroup(groupid uint) (*Group, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGroup", groupid)
	ret0, _ := ret[0].(*Group)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGroup indicates an expected call of GetGroup.
func (mr *MockManagerMockRecorder) GetGroup(groupid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGroup", reflect.TypeOf((*MockManager)(nil).GetGroup), groupid)
}

// GetServersStatus mocks base method.
func (m *MockManager) GetServersStatus() []v1.GroupInfo {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetServersStatus")
	ret0, _ := ret[0].([]v1.GroupInfo)
	return ret0
}

// GetServersStatus indicates an expected call of GetServersStatus.
func (mr *MockManagerMockRecorder) GetServersStatus() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetServersStatus", reflect.TypeOf((*MockManager)(nil).GetServersStatus))
}

// InsertGroup mocks base method.
func (m *MockManager) InsertGroup(group v1.Group) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertGroup", group)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertGroup indicates an expected call of InsertGroup.
func (mr *MockManagerMockRecorder) InsertGroup(group any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertGroup", reflect.TypeOf((*MockManager)(nil).InsertGroup), group)
}

// InsertHost mocks base method.
func (m *MockManager) InsertHost(host v1.Host) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertHost", host)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertHost indicates an expected call of InsertHost.
func (mr *MockManagerMockRecorder) InsertHost(host any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertHost", reflect.TypeOf((*MockManager)(nil).InsertHost), host)
}

// Range mocks base method.
func (m *MockManager) Range(arg0 func(sort_map.Keyer, any) bool) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Range", arg0)
}

// Range indicates an expected call of Range.
func (mr *MockManagerMockRecorder) Range(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Range", reflect.TypeOf((*MockManager)(nil).Range), arg0)
}

// RemoveAll mocks base method.
func (m *MockManager) RemoveAll() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveAll")
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveAll indicates an expected call of RemoveAll.
func (mr *MockManagerMockRecorder) RemoveAll() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveAll", reflect.TypeOf((*MockManager)(nil).RemoveAll))
}

// RemoveGroupByID mocks base method.
func (m *MockManager) RemoveGroupByID(groupid uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveGroupByID", groupid)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveGroupByID indicates an expected call of RemoveGroupByID.
func (mr *MockManagerMockRecorder) RemoveGroupByID(groupid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveGroupByID", reflect.TypeOf((*MockManager)(nil).RemoveGroupByID), groupid)
}

// RemoveHost mocks base method.
func (m *MockManager) RemoveHost(host v1.Host) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveHost", host)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveHost indicates an expected call of RemoveHost.
func (mr *MockManagerMockRecorder) RemoveHost(host any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveHost", reflect.TypeOf((*MockManager)(nil).RemoveHost), host)
}

// SyncServersStatus mocks base method.
func (m *MockManager) SyncServersStatus() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SyncServersStatus")
}

// SyncServersStatus indicates an expected call of SyncServersStatus.
func (mr *MockManagerMockRecorder) SyncServersStatus() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SyncServersStatus", reflect.TypeOf((*MockManager)(nil).SyncServersStatus))
}

// UpdateGroup mocks base method.
func (m *MockManager) UpdateGroup(old, new v1.Group) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateGroup", old, new)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateGroup indicates an expected call of UpdateGroup.
func (mr *MockManagerMockRecorder) UpdateGroup(old, new any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateGroup", reflect.TypeOf((*MockManager)(nil).UpdateGroup), old, new)
}

// UpdateHost mocks base method.
func (m *MockManager) UpdateHost(old, new v1.Host) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateHost", old, new)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateHost indicates an expected call of UpdateHost.
func (mr *MockManagerMockRecorder) UpdateHost(old, new any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateHost", reflect.TypeOf((*MockManager)(nil).UpdateHost), old, new)
}
