// Code generated by MockGen. DO NOT EDIT.
// Source: web_server_config.go
//
// Generated by this command:
//
//	mockgen -source=web_server_config.go -destination=generics_mock_web_server_config.go -package=v1 gin-vue-admin/internal/hmdr_api/service/v1 WebServerConfigSrv
//

// Package v1 is a generated GoMock package.
package v1

import (
	context "context"
	v1 "gin-vue-admin/api/heimdallr_api/v1"
	v10 "gin-vue-admin/internal/pkg/meta/v1"
	reflect "reflect"

	context0 "github.com/ClessLi/bifrost/pkg/resolv/V3/nginx/configuration/context"
	utils "github.com/ClessLi/bifrost/pkg/resolv/V3/nginx/configuration/utils"
	gomock "go.uber.org/mock/gomock"
)

// MockWebServerConfigSrv is a mock of WebServerConfigSrv interface.
type MockWebServerConfigSrv struct {
	ctrl     *gomock.Controller
	recorder *MockWebServerConfigSrvMockRecorder
}

// MockWebServerConfigSrvMockRecorder is the mock recorder for MockWebServerConfigSrv.
type MockWebServerConfigSrvMockRecorder struct {
	mock *MockWebServerConfigSrv
}

// NewMockWebServerConfigSrv creates a new mock instance.
func NewMockWebServerConfigSrv(ctrl *gomock.Controller) *MockWebServerConfigSrv {
	mock := &MockWebServerConfigSrv{ctrl: ctrl}
	mock.recorder = &MockWebServerConfigSrvMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWebServerConfigSrv) EXPECT() *MockWebServerConfigSrvMockRecorder {
	return m.recorder
}

// ChangeContextEnabledState mocks base method.
func (m *MockWebServerConfigSrv) ChangeContextEnabledState(ctx context.Context, opts v10.WebServerOptions, ofp utils.ConfigFingerprints, ctxmeta v10.TargetConfigContextOptions[v10.ConfigContextEnabledStateMeta]) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChangeContextEnabledState", ctx, opts, ofp, ctxmeta)
	ret0, _ := ret[0].(error)
	return ret0
}

// ChangeContextEnabledState indicates an expected call of ChangeContextEnabledState.
func (mr *MockWebServerConfigSrvMockRecorder) ChangeContextEnabledState(ctx, opts, ofp, ctxmeta any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChangeContextEnabledState", reflect.TypeOf((*MockWebServerConfigSrv)(nil).ChangeContextEnabledState), ctx, opts, ofp, ctxmeta)
}

// GetConfig mocks base method.
func (m *MockWebServerConfigSrv) GetConfig(ctx context.Context, opts v10.WebServerOptions) (v10.WebServerConfig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConfig", ctx, opts)
	ret0, _ := ret[0].(v10.WebServerConfig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetConfig indicates an expected call of GetConfig.
func (mr *MockWebServerConfigSrvMockRecorder) GetConfig(ctx, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConfig", reflect.TypeOf((*MockWebServerConfigSrv)(nil).GetConfig), ctx, opts)
}

// GetContext mocks base method.
func (m *MockWebServerConfigSrv) GetContext(ctx context.Context, opts v10.WebServerOptions, pos v10.ConfigContextPos) (context0.Context, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetContext", ctx, opts, pos)
	ret0, _ := ret[0].(context0.Context)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetContext indicates an expected call of GetContext.
func (mr *MockWebServerConfigSrvMockRecorder) GetContext(ctx, opts, pos any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetContext", reflect.TypeOf((*MockWebServerConfigSrv)(nil).GetContext), ctx, opts, pos)
}

// GetIncludedConfigs mocks base method.
func (m *MockWebServerConfigSrv) GetIncludedConfigs(ctx context.Context, opts v10.WebServerOptions, pos v10.ConfigContextPos) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIncludedConfigs", ctx, opts, pos)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetIncludedConfigs indicates an expected call of GetIncludedConfigs.
func (mr *MockWebServerConfigSrvMockRecorder) GetIncludedConfigs(ctx, opts, pos any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIncludedConfigs", reflect.TypeOf((*MockWebServerConfigSrv)(nil).GetIncludedConfigs), ctx, opts, pos)
}

// GetOptions mocks base method.
func (m *MockWebServerConfigSrv) GetOptions(ctx context.Context) ([]v1.BifrostGroupMeta, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOptions", ctx)
	ret0, _ := ret[0].([]v1.BifrostGroupMeta)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOptions indicates an expected call of GetOptions.
func (mr *MockWebServerConfigSrvMockRecorder) GetOptions(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOptions", reflect.TypeOf((*MockWebServerConfigSrv)(nil).GetOptions), ctx)
}

// InsertWithClone mocks base method.
func (m *MockWebServerConfigSrv) InsertWithClone(ctx context.Context, opts v10.WebServerOptions, ofp utils.ConfigFingerprints, ctxmeta v10.TargetConfigContextOptions[v10.CloneConfigContextMeta]) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertWithClone", ctx, opts, ofp, ctxmeta)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertWithClone indicates an expected call of InsertWithClone.
func (mr *MockWebServerConfigSrvMockRecorder) InsertWithClone(ctx, opts, ofp, ctxmeta any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertWithClone", reflect.TypeOf((*MockWebServerConfigSrv)(nil).InsertWithClone), ctx, opts, ofp, ctxmeta)
}

// InsertWithNew mocks base method.
func (m *MockWebServerConfigSrv) InsertWithNew(ctx context.Context, opts v10.WebServerOptions, ofp utils.ConfigFingerprints, ctxmeta v10.TargetConfigContextOptions[v10.NewConfigContextMeta]) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertWithNew", ctx, opts, ofp, ctxmeta)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertWithNew indicates an expected call of InsertWithNew.
func (mr *MockWebServerConfigSrvMockRecorder) InsertWithNew(ctx, opts, ofp, ctxmeta any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertWithNew", reflect.TypeOf((*MockWebServerConfigSrv)(nil).InsertWithNew), ctx, opts, ofp, ctxmeta)
}

// ModifyContextValue mocks base method.
func (m *MockWebServerConfigSrv) ModifyContextValue(ctx context.Context, opts v10.WebServerOptions, ofp utils.ConfigFingerprints, ctxmeta v10.TargetConfigContextOptions[v10.NewConfigContextMeta]) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ModifyContextValue", ctx, opts, ofp, ctxmeta)
	ret0, _ := ret[0].(error)
	return ret0
}

// ModifyContextValue indicates an expected call of ModifyContextValue.
func (mr *MockWebServerConfigSrvMockRecorder) ModifyContextValue(ctx, opts, ofp, ctxmeta any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ModifyContextValue", reflect.TypeOf((*MockWebServerConfigSrv)(nil).ModifyContextValue), ctx, opts, ofp, ctxmeta)
}

// ModifyWithClone mocks base method.
func (m *MockWebServerConfigSrv) ModifyWithClone(ctx context.Context, opts v10.WebServerOptions, ofp utils.ConfigFingerprints, ctxmeta v10.TargetConfigContextOptions[v10.CloneConfigContextMeta]) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ModifyWithClone", ctx, opts, ofp, ctxmeta)
	ret0, _ := ret[0].(error)
	return ret0
}

// ModifyWithClone indicates an expected call of ModifyWithClone.
func (mr *MockWebServerConfigSrvMockRecorder) ModifyWithClone(ctx, opts, ofp, ctxmeta any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ModifyWithClone", reflect.TypeOf((*MockWebServerConfigSrv)(nil).ModifyWithClone), ctx, opts, ofp, ctxmeta)
}

// ModifyWithNew mocks base method.
func (m *MockWebServerConfigSrv) ModifyWithNew(ctx context.Context, opts v10.WebServerOptions, ofp utils.ConfigFingerprints, ctxmeta v10.TargetConfigContextOptions[v10.NewConfigContextMeta]) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ModifyWithNew", ctx, opts, ofp, ctxmeta)
	ret0, _ := ret[0].(error)
	return ret0
}

// ModifyWithNew indicates an expected call of ModifyWithNew.
func (mr *MockWebServerConfigSrvMockRecorder) ModifyWithNew(ctx, opts, ofp, ctxmeta any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ModifyWithNew", reflect.TypeOf((*MockWebServerConfigSrv)(nil).ModifyWithNew), ctx, opts, ofp, ctxmeta)
}

// Move mocks base method.
func (m *MockWebServerConfigSrv) Move(ctx context.Context, opts v10.WebServerOptions, ofp utils.ConfigFingerprints, ctxmeta v10.TargetConfigContextOptions[v10.CloneConfigContextMeta]) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Move", ctx, opts, ofp, ctxmeta)
	ret0, _ := ret[0].(error)
	return ret0
}

// Move indicates an expected call of Move.
func (mr *MockWebServerConfigSrvMockRecorder) Move(ctx, opts, ofp, ctxmeta any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Move", reflect.TypeOf((*MockWebServerConfigSrv)(nil).Move), ctx, opts, ofp, ctxmeta)
}

// Remove mocks base method.
func (m *MockWebServerConfigSrv) Remove(ctx context.Context, opts v10.WebServerOptions, ofp utils.ConfigFingerprints, pos v10.ConfigContextPos) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Remove", ctx, opts, ofp, pos)
	ret0, _ := ret[0].(error)
	return ret0
}

// Remove indicates an expected call of Remove.
func (mr *MockWebServerConfigSrvMockRecorder) Remove(ctx, opts, ofp, pos any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Remove", reflect.TypeOf((*MockWebServerConfigSrv)(nil).Remove), ctx, opts, ofp, pos)
}
