// Code generated by MockGen. DO NOT EDIT.
// Source: gin-vue-admin/internal/hmdr_api/service/v1 (interfaces: Factory,AgentInfoSrv,GroupSrv,HostSrv,WebServerLogWatcherSrv,WebServerStatisticsSrv,WebServerConfigSrv,WebServerBinCMDSrv)
//
// Generated by this command:
//
//	mockgen -self_package=gin-vue-admin/internal/hmdr_api/service/v1 -destination=mock_service.go -package=v1 gin-vue-admin/internal/hmdr_api/service/v1 Factory,AgentInfoSrv,GroupSrv,HostSrv,WebServerLogWatcherSrv,WebServerStatisticsSrv,WebServerConfigSrv,WebServerBinCMDSrv
//

// Package v1 is a generated GoMock package.
package v1

import (
	context "context"
	v1 "gin-vue-admin/api/heimdallr_api/v1"
	v10 "gin-vue-admin/internal/pkg/meta/v1"
	reflect "reflect"

	context0 "github.com/ClessLi/bifrost/pkg/resolv/V3/nginx/configuration/context"
	utils "github.com/ClessLi/bifrost/pkg/resolv/V3/nginx/configuration/utils"
	gomock "go.uber.org/mock/gomock"
)

// MockFactory is a mock of Factory interface.
type MockFactory struct {
	ctrl     *gomock.Controller
	recorder *MockFactoryMockRecorder
	isgomock struct{}
}

// MockFactoryMockRecorder is the mock recorder for MockFactory.
type MockFactoryMockRecorder struct {
	mock *MockFactory
}

// NewMockFactory creates a new mock instance.
func NewMockFactory(ctrl *gomock.Controller) *MockFactory {
	mock := &MockFactory{ctrl: ctrl}
	mock.recorder = &MockFactoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFactory) EXPECT() *MockFactoryMockRecorder {
	return m.recorder
}

// AgentInfos mocks base method.
func (m *MockFactory) AgentInfos() AgentInfoSrv {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AgentInfos")
	ret0, _ := ret[0].(AgentInfoSrv)
	return ret0
}

// AgentInfos indicates an expected call of AgentInfos.
func (mr *MockFactoryMockRecorder) AgentInfos() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AgentInfos", reflect.TypeOf((*MockFactory)(nil).AgentInfos))
}

// Groups mocks base method.
func (m *MockFactory) Groups() GroupSrv {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Groups")
	ret0, _ := ret[0].(GroupSrv)
	return ret0
}

// Groups indicates an expected call of Groups.
func (mr *MockFactoryMockRecorder) Groups() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Groups", reflect.TypeOf((*MockFactory)(nil).Groups))
}

// Hosts mocks base method.
func (m *MockFactory) Hosts() HostSrv {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Hosts")
	ret0, _ := ret[0].(HostSrv)
	return ret0
}

// Hosts indicates an expected call of Hosts.
func (mr *MockFactoryMockRecorder) Hosts() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Hosts", reflect.TypeOf((*MockFactory)(nil).Hosts))
}

// WebServerBinCMD mocks base method.
func (m *MockFactory) WebServerBinCMD() WebServerBinCMDSrv {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WebServerBinCMD")
	ret0, _ := ret[0].(WebServerBinCMDSrv)
	return ret0
}

// WebServerBinCMD indicates an expected call of WebServerBinCMD.
func (mr *MockFactoryMockRecorder) WebServerBinCMD() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WebServerBinCMD", reflect.TypeOf((*MockFactory)(nil).WebServerBinCMD))
}

// WebServerConfigs mocks base method.
func (m *MockFactory) WebServerConfigs() WebServerConfigSrv {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WebServerConfigs")
	ret0, _ := ret[0].(WebServerConfigSrv)
	return ret0
}

// WebServerConfigs indicates an expected call of WebServerConfigs.
func (mr *MockFactoryMockRecorder) WebServerConfigs() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WebServerConfigs", reflect.TypeOf((*MockFactory)(nil).WebServerConfigs))
}

// WebServerLogWatchers mocks base method.
func (m *MockFactory) WebServerLogWatchers() WebServerLogWatcherSrv {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WebServerLogWatchers")
	ret0, _ := ret[0].(WebServerLogWatcherSrv)
	return ret0
}

// WebServerLogWatchers indicates an expected call of WebServerLogWatchers.
func (mr *MockFactoryMockRecorder) WebServerLogWatchers() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WebServerLogWatchers", reflect.TypeOf((*MockFactory)(nil).WebServerLogWatchers))
}

// WebServerStatistics mocks base method.
func (m *MockFactory) WebServerStatistics() WebServerStatisticsSrv {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WebServerStatistics")
	ret0, _ := ret[0].(WebServerStatisticsSrv)
	return ret0
}

// WebServerStatistics indicates an expected call of WebServerStatistics.
func (mr *MockFactoryMockRecorder) WebServerStatistics() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WebServerStatistics", reflect.TypeOf((*MockFactory)(nil).WebServerStatistics))
}

// MockAgentInfoSrv is a mock of AgentInfoSrv interface.
type MockAgentInfoSrv struct {
	ctrl     *gomock.Controller
	recorder *MockAgentInfoSrvMockRecorder
	isgomock struct{}
}

// MockAgentInfoSrvMockRecorder is the mock recorder for MockAgentInfoSrv.
type MockAgentInfoSrvMockRecorder struct {
	mock *MockAgentInfoSrv
}

// NewMockAgentInfoSrv creates a new mock instance.
func NewMockAgentInfoSrv(ctrl *gomock.Controller) *MockAgentInfoSrv {
	mock := &MockAgentInfoSrv{ctrl: ctrl}
	mock.recorder = &MockAgentInfoSrvMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAgentInfoSrv) EXPECT() *MockAgentInfoSrvMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockAgentInfoSrv) Get(ctx context.Context) ([]v1.GroupInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx)
	ret0, _ := ret[0].([]v1.GroupInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockAgentInfoSrvMockRecorder) Get(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockAgentInfoSrv)(nil).Get), ctx)
}

// MockGroupSrv is a mock of GroupSrv interface.
type MockGroupSrv struct {
	ctrl     *gomock.Controller
	recorder *MockGroupSrvMockRecorder
	isgomock struct{}
}

// MockGroupSrvMockRecorder is the mock recorder for MockGroupSrv.
type MockGroupSrvMockRecorder struct {
	mock *MockGroupSrv
}

// NewMockGroupSrv creates a new mock instance.
func NewMockGroupSrv(ctrl *gomock.Controller) *MockGroupSrv {
	mock := &MockGroupSrv{ctrl: ctrl}
	mock.recorder = &MockGroupSrvMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGroupSrv) EXPECT() *MockGroupSrvMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockGroupSrv) Create(ctx context.Context, group v1.Group) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, group)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockGroupSrvMockRecorder) Create(ctx, group any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockGroupSrv)(nil).Create), ctx, group)
}

// Delete mocks base method.
func (m *MockGroupSrv) Delete(ctx context.Context, groupid uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, groupid)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockGroupSrvMockRecorder) Delete(ctx, groupid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockGroupSrv)(nil).Delete), ctx, groupid)
}

// DeleteCollections mocks base method.
func (m *MockGroupSrv) DeleteCollections(ctx context.Context, ids v10.IDsOptions) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCollections", ctx, ids)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteCollections indicates an expected call of DeleteCollections.
func (mr *MockGroupSrvMockRecorder) DeleteCollections(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCollections", reflect.TypeOf((*MockGroupSrv)(nil).DeleteCollections), ctx, ids)
}

// Get mocks base method.
func (m *MockGroupSrv) Get(ctx context.Context, groupid uint) (v1.Group, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, groupid)
	ret0, _ := ret[0].(v1.Group)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockGroupSrvMockRecorder) Get(ctx, groupid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockGroupSrv)(nil).Get), ctx, groupid)
}

// List mocks base method.
func (m *MockGroupSrv) List(ctx context.Context, opts v10.ListOptions) (v1.GroupList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, opts)
	ret0, _ := ret[0].(v1.GroupList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockGroupSrvMockRecorder) List(ctx, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockGroupSrv)(nil).List), ctx, opts)
}

// Update mocks base method.
func (m *MockGroupSrv) Update(ctx context.Context, group v1.Group) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, group)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockGroupSrvMockRecorder) Update(ctx, group any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockGroupSrv)(nil).Update), ctx, group)
}

// MockHostSrv is a mock of HostSrv interface.
type MockHostSrv struct {
	ctrl     *gomock.Controller
	recorder *MockHostSrvMockRecorder
	isgomock struct{}
}

// MockHostSrvMockRecorder is the mock recorder for MockHostSrv.
type MockHostSrvMockRecorder struct {
	mock *MockHostSrv
}

// NewMockHostSrv creates a new mock instance.
func NewMockHostSrv(ctrl *gomock.Controller) *MockHostSrv {
	mock := &MockHostSrv{ctrl: ctrl}
	mock.recorder = &MockHostSrvMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHostSrv) EXPECT() *MockHostSrvMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockHostSrv) Create(ctx context.Context, host v1.Host) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, host)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockHostSrvMockRecorder) Create(ctx, host any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockHostSrv)(nil).Create), ctx, host)
}

// Delete mocks base method.
func (m *MockHostSrv) Delete(ctx context.Context, hostid uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, hostid)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockHostSrvMockRecorder) Delete(ctx, hostid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockHostSrv)(nil).Delete), ctx, hostid)
}

// DeleteCollection mocks base method.
func (m *MockHostSrv) DeleteCollection(ctx context.Context, ids v10.IDsOptions) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCollection", ctx, ids)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteCollection indicates an expected call of DeleteCollection.
func (mr *MockHostSrvMockRecorder) DeleteCollection(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCollection", reflect.TypeOf((*MockHostSrv)(nil).DeleteCollection), ctx, ids)
}

// Get mocks base method.
func (m *MockHostSrv) Get(ctx context.Context, hostid uint) (v1.Host, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, hostid)
	ret0, _ := ret[0].(v1.Host)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockHostSrvMockRecorder) Get(ctx, hostid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockHostSrv)(nil).Get), ctx, hostid)
}

// List mocks base method.
func (m *MockHostSrv) List(ctx context.Context, opts v10.ListOptions) (v1.HostList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, opts)
	ret0, _ := ret[0].(v1.HostList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockHostSrvMockRecorder) List(ctx, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockHostSrv)(nil).List), ctx, opts)
}

// Update mocks base method.
func (m *MockHostSrv) Update(ctx context.Context, host v1.Host) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, host)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockHostSrvMockRecorder) Update(ctx, host any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockHostSrv)(nil).Update), ctx, host)
}

// MockWebServerLogWatcherSrv is a mock of WebServerLogWatcherSrv interface.
type MockWebServerLogWatcherSrv struct {
	ctrl     *gomock.Controller
	recorder *MockWebServerLogWatcherSrvMockRecorder
	isgomock struct{}
}

// MockWebServerLogWatcherSrvMockRecorder is the mock recorder for MockWebServerLogWatcherSrv.
type MockWebServerLogWatcherSrvMockRecorder struct {
	mock *MockWebServerLogWatcherSrv
}

// NewMockWebServerLogWatcherSrv creates a new mock instance.
func NewMockWebServerLogWatcherSrv(ctrl *gomock.Controller) *MockWebServerLogWatcherSrv {
	mock := &MockWebServerLogWatcherSrv{ctrl: ctrl}
	mock.recorder = &MockWebServerLogWatcherSrvMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWebServerLogWatcherSrv) EXPECT() *MockWebServerLogWatcherSrvMockRecorder {
	return m.recorder
}

// Watch mocks base method.
func (m *MockWebServerLogWatcherSrv) Watch(ctx context.Context, opts v10.WebServerLogOptions) (<-chan []byte, context.CancelFunc, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Watch", ctx, opts)
	ret0, _ := ret[0].(<-chan []byte)
	ret1, _ := ret[1].(context.CancelFunc)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Watch indicates an expected call of Watch.
func (mr *MockWebServerLogWatcherSrvMockRecorder) Watch(ctx, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Watch", reflect.TypeOf((*MockWebServerLogWatcherSrv)(nil).Watch), ctx, opts)
}

// MockWebServerStatisticsSrv is a mock of WebServerStatisticsSrv interface.
type MockWebServerStatisticsSrv struct {
	ctrl     *gomock.Controller
	recorder *MockWebServerStatisticsSrvMockRecorder
	isgomock struct{}
}

// MockWebServerStatisticsSrvMockRecorder is the mock recorder for MockWebServerStatisticsSrv.
type MockWebServerStatisticsSrvMockRecorder struct {
	mock *MockWebServerStatisticsSrv
}

// NewMockWebServerStatisticsSrv creates a new mock instance.
func NewMockWebServerStatisticsSrv(ctrl *gomock.Controller) *MockWebServerStatisticsSrv {
	mock := &MockWebServerStatisticsSrv{ctrl: ctrl}
	mock.recorder = &MockWebServerStatisticsSrvMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWebServerStatisticsSrv) EXPECT() *MockWebServerStatisticsSrvMockRecorder {
	return m.recorder
}

// ConnectivityCheckOfProxyService mocks base method.
func (m *MockWebServerStatisticsSrv) ConnectivityCheckOfProxyService(ctx context.Context, opts v10.WebServerOptions, proxyPassPos v10.ConfigContextPos) (v1.ProxyServiceInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConnectivityCheckOfProxyService", ctx, opts, proxyPassPos)
	ret0, _ := ret[0].(v1.ProxyServiceInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ConnectivityCheckOfProxyService indicates an expected call of ConnectivityCheckOfProxyService.
func (mr *MockWebServerStatisticsSrvMockRecorder) ConnectivityCheckOfProxyService(ctx, opts, proxyPassPos any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConnectivityCheckOfProxyService", reflect.TypeOf((*MockWebServerStatisticsSrv)(nil).ConnectivityCheckOfProxyService), ctx, opts, proxyPassPos)
}

// ExportProxyServiceInfoToExcel mocks base method.
func (m *MockWebServerStatisticsSrv) ExportProxyServiceInfoToExcel(ctx context.Context, opts v10.WebServerOptions) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExportProxyServiceInfoToExcel", ctx, opts)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExportProxyServiceInfoToExcel indicates an expected call of ExportProxyServiceInfoToExcel.
func (mr *MockWebServerStatisticsSrvMockRecorder) ExportProxyServiceInfoToExcel(ctx, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExportProxyServiceInfoToExcel", reflect.TypeOf((*MockWebServerStatisticsSrv)(nil).ExportProxyServiceInfoToExcel), ctx, opts)
}

// GetProxyServiceInfo mocks base method.
func (m *MockWebServerStatisticsSrv) GetProxyServiceInfo(ctx context.Context, opts v10.WebServerOptions) ([]v1.ProxyServiceInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProxyServiceInfo", ctx, opts)
	ret0, _ := ret[0].([]v1.ProxyServiceInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProxyServiceInfo indicates an expected call of GetProxyServiceInfo.
func (mr *MockWebServerStatisticsSrvMockRecorder) GetProxyServiceInfo(ctx, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProxyServiceInfo", reflect.TypeOf((*MockWebServerStatisticsSrv)(nil).GetProxyServiceInfo), ctx, opts)
}

// MockWebServerConfigSrv is a mock of WebServerConfigSrv interface.
type MockWebServerConfigSrv struct {
	ctrl     *gomock.Controller
	recorder *MockWebServerConfigSrvMockRecorder
	isgomock struct{}
}

// MockWebServerConfigSrvMockRecorder is the mock recorder for MockWebServerConfigSrv.
type MockWebServerConfigSrvMockRecorder struct {
	mock *MockWebServerConfigSrv
}

// NewMockWebServerConfigSrv creates a new mock instance.
func NewMockWebServerConfigSrv(ctrl *gomock.Controller) *MockWebServerConfigSrv {
	mock := &MockWebServerConfigSrv{ctrl: ctrl}
	mock.recorder = &MockWebServerConfigSrvMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWebServerConfigSrv) EXPECT() *MockWebServerConfigSrvMockRecorder {
	return m.recorder
}

// ChangeContextEnabledState mocks base method.
func (m *MockWebServerConfigSrv) ChangeContextEnabledState(ctx context.Context, opts v10.WebServerOptions, ofp utils.ConfigFingerprints, ctxmeta v10.TargetConfigContextOptions[v10.ConfigContextEnabledStateMeta]) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChangeContextEnabledState", ctx, opts, ofp, ctxmeta)
	ret0, _ := ret[0].(error)
	return ret0
}

// ChangeContextEnabledState indicates an expected call of ChangeContextEnabledState.
func (mr *MockWebServerConfigSrvMockRecorder) ChangeContextEnabledState(ctx, opts, ofp, ctxmeta any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChangeContextEnabledState", reflect.TypeOf((*MockWebServerConfigSrv)(nil).ChangeContextEnabledState), ctx, opts, ofp, ctxmeta)
}

// GetConfig mocks base method.
func (m *MockWebServerConfigSrv) GetConfig(ctx context.Context, opts v10.WebServerOptions) (v10.WebServerConfig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConfig", ctx, opts)
	ret0, _ := ret[0].(v10.WebServerConfig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetConfig indicates an expected call of GetConfig.
func (mr *MockWebServerConfigSrvMockRecorder) GetConfig(ctx, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConfig", reflect.TypeOf((*MockWebServerConfigSrv)(nil).GetConfig), ctx, opts)
}

// GetContext mocks base method.
func (m *MockWebServerConfigSrv) GetContext(ctx context.Context, opts v10.WebServerOptions, ofp utils.ConfigFingerprints, pos v10.ConfigContextPos) (context0.Context, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetContext", ctx, opts, ofp, pos)
	ret0, _ := ret[0].(context0.Context)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetContext indicates an expected call of GetContext.
func (mr *MockWebServerConfigSrvMockRecorder) GetContext(ctx, opts, ofp, pos any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetContext", reflect.TypeOf((*MockWebServerConfigSrv)(nil).GetContext), ctx, opts, ofp, pos)
}

// GetIncludedConfigs mocks base method.
func (m *MockWebServerConfigSrv) GetIncludedConfigs(ctx context.Context, opts v10.WebServerOptions, ofp utils.ConfigFingerprints, pos v10.ConfigContextPos) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIncludedConfigs", ctx, opts, ofp, pos)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetIncludedConfigs indicates an expected call of GetIncludedConfigs.
func (mr *MockWebServerConfigSrvMockRecorder) GetIncludedConfigs(ctx, opts, ofp, pos any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIncludedConfigs", reflect.TypeOf((*MockWebServerConfigSrv)(nil).GetIncludedConfigs), ctx, opts, ofp, pos)
}

// GetOptions mocks base method.
func (m *MockWebServerConfigSrv) GetOptions(ctx context.Context) ([]v1.BifrostGroupMeta, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOptions", ctx)
	ret0, _ := ret[0].([]v1.BifrostGroupMeta)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOptions indicates an expected call of GetOptions.
func (mr *MockWebServerConfigSrvMockRecorder) GetOptions(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOptions", reflect.TypeOf((*MockWebServerConfigSrv)(nil).GetOptions), ctx)
}

// InsertWithClone mocks base method.
func (m *MockWebServerConfigSrv) InsertWithClone(ctx context.Context, opts v10.WebServerOptions, ofp utils.ConfigFingerprints, ctxmeta v10.TargetConfigContextOptions[v10.CloneConfigContextMeta], disabledTarget bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertWithClone", ctx, opts, ofp, ctxmeta, disabledTarget)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertWithClone indicates an expected call of InsertWithClone.
func (mr *MockWebServerConfigSrvMockRecorder) InsertWithClone(ctx, opts, ofp, ctxmeta, disabledTarget any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertWithClone", reflect.TypeOf((*MockWebServerConfigSrv)(nil).InsertWithClone), ctx, opts, ofp, ctxmeta, disabledTarget)
}

// InsertWithNew mocks base method.
func (m *MockWebServerConfigSrv) InsertWithNew(ctx context.Context, opts v10.WebServerOptions, ofp utils.ConfigFingerprints, ctxmeta v10.TargetConfigContextOptions[v10.NewConfigContextMeta], disabledTarget bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertWithNew", ctx, opts, ofp, ctxmeta, disabledTarget)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertWithNew indicates an expected call of InsertWithNew.
func (mr *MockWebServerConfigSrvMockRecorder) InsertWithNew(ctx, opts, ofp, ctxmeta, disabledTarget any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertWithNew", reflect.TypeOf((*MockWebServerConfigSrv)(nil).InsertWithNew), ctx, opts, ofp, ctxmeta, disabledTarget)
}

// ModifyContextValue mocks base method.
func (m *MockWebServerConfigSrv) ModifyContextValue(ctx context.Context, opts v10.WebServerOptions, ofp utils.ConfigFingerprints, ctxmeta v10.TargetConfigContextOptions[v10.NewConfigContextMeta]) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ModifyContextValue", ctx, opts, ofp, ctxmeta)
	ret0, _ := ret[0].(error)
	return ret0
}

// ModifyContextValue indicates an expected call of ModifyContextValue.
func (mr *MockWebServerConfigSrvMockRecorder) ModifyContextValue(ctx, opts, ofp, ctxmeta any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ModifyContextValue", reflect.TypeOf((*MockWebServerConfigSrv)(nil).ModifyContextValue), ctx, opts, ofp, ctxmeta)
}

// ModifyWithClone mocks base method.
func (m *MockWebServerConfigSrv) ModifyWithClone(ctx context.Context, opts v10.WebServerOptions, ofp utils.ConfigFingerprints, ctxmeta v10.TargetConfigContextOptions[v10.CloneConfigContextMeta]) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ModifyWithClone", ctx, opts, ofp, ctxmeta)
	ret0, _ := ret[0].(error)
	return ret0
}

// ModifyWithClone indicates an expected call of ModifyWithClone.
func (mr *MockWebServerConfigSrvMockRecorder) ModifyWithClone(ctx, opts, ofp, ctxmeta any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ModifyWithClone", reflect.TypeOf((*MockWebServerConfigSrv)(nil).ModifyWithClone), ctx, opts, ofp, ctxmeta)
}

// ModifyWithNew mocks base method.
func (m *MockWebServerConfigSrv) ModifyWithNew(ctx context.Context, opts v10.WebServerOptions, ofp utils.ConfigFingerprints, ctxmeta v10.TargetConfigContextOptions[v10.NewConfigContextMeta]) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ModifyWithNew", ctx, opts, ofp, ctxmeta)
	ret0, _ := ret[0].(error)
	return ret0
}

// ModifyWithNew indicates an expected call of ModifyWithNew.
func (mr *MockWebServerConfigSrvMockRecorder) ModifyWithNew(ctx, opts, ofp, ctxmeta any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ModifyWithNew", reflect.TypeOf((*MockWebServerConfigSrv)(nil).ModifyWithNew), ctx, opts, ofp, ctxmeta)
}

// Move mocks base method.
func (m *MockWebServerConfigSrv) Move(ctx context.Context, opts v10.WebServerOptions, ofp utils.ConfigFingerprints, ctxmeta v10.TargetConfigContextOptions[v10.CloneConfigContextMeta], disabledTarget bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Move", ctx, opts, ofp, ctxmeta, disabledTarget)
	ret0, _ := ret[0].(error)
	return ret0
}

// Move indicates an expected call of Move.
func (mr *MockWebServerConfigSrvMockRecorder) Move(ctx, opts, ofp, ctxmeta, disabledTarget any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Move", reflect.TypeOf((*MockWebServerConfigSrv)(nil).Move), ctx, opts, ofp, ctxmeta, disabledTarget)
}

// Remove mocks base method.
func (m *MockWebServerConfigSrv) Remove(ctx context.Context, opts v10.WebServerOptions, ofp utils.ConfigFingerprints, pos v10.ConfigContextPos) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Remove", ctx, opts, ofp, pos)
	ret0, _ := ret[0].(error)
	return ret0
}

// Remove indicates an expected call of Remove.
func (mr *MockWebServerConfigSrvMockRecorder) Remove(ctx, opts, ofp, pos any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Remove", reflect.TypeOf((*MockWebServerConfigSrv)(nil).Remove), ctx, opts, ofp, pos)
}

// SearchContextPositions mocks base method.
func (m *MockWebServerConfigSrv) SearchContextPositions(ctx context.Context, opts v10.WebServerOptions, ofp utils.ConfigFingerprints, kwmeta v10.SearchKeywordsMeta) ([]v10.ConfigContextPos, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchContextPositions", ctx, opts, ofp, kwmeta)
	ret0, _ := ret[0].([]v10.ConfigContextPos)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchContextPositions indicates an expected call of SearchContextPositions.
func (mr *MockWebServerConfigSrvMockRecorder) SearchContextPositions(ctx, opts, ofp, kwmeta any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchContextPositions", reflect.TypeOf((*MockWebServerConfigSrv)(nil).SearchContextPositions), ctx, opts, ofp, kwmeta)
}

// UpdateConfig mocks base method.
func (m *MockWebServerConfigSrv) UpdateConfig(ctx context.Context, opts v10.WebServerOptions, ofp utils.ConfigFingerprints, configJsonData []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateConfig", ctx, opts, ofp, configJsonData)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateConfig indicates an expected call of UpdateConfig.
func (mr *MockWebServerConfigSrvMockRecorder) UpdateConfig(ctx, opts, ofp, configJsonData any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateConfig", reflect.TypeOf((*MockWebServerConfigSrv)(nil).UpdateConfig), ctx, opts, ofp, configJsonData)
}

// MockWebServerBinCMDSrv is a mock of WebServerBinCMDSrv interface.
type MockWebServerBinCMDSrv struct {
	ctrl     *gomock.Controller
	recorder *MockWebServerBinCMDSrvMockRecorder
	isgomock struct{}
}

// MockWebServerBinCMDSrvMockRecorder is the mock recorder for MockWebServerBinCMDSrv.
type MockWebServerBinCMDSrvMockRecorder struct {
	mock *MockWebServerBinCMDSrv
}

// NewMockWebServerBinCMDSrv creates a new mock instance.
func NewMockWebServerBinCMDSrv(ctrl *gomock.Controller) *MockWebServerBinCMDSrv {
	mock := &MockWebServerBinCMDSrv{ctrl: ctrl}
	mock.recorder = &MockWebServerBinCMDSrvMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWebServerBinCMDSrv) EXPECT() *MockWebServerBinCMDSrvMockRecorder {
	return m.recorder
}

// Exec mocks base method.
func (m *MockWebServerBinCMDSrv) Exec(ctx context.Context, opts v10.WebServerOptions, arg ...string) (v10.WebServerBinCMDExecResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, opts}
	for _, a := range arg {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Exec", varargs...)
	ret0, _ := ret[0].(v10.WebServerBinCMDExecResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Exec indicates an expected call of Exec.
func (mr *MockWebServerBinCMDSrvMockRecorder) Exec(ctx, opts any, arg ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, opts}, arg...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exec", reflect.TypeOf((*MockWebServerBinCMDSrv)(nil).Exec), varargs...)
}
