// Code generated by MockGen. DO NOT EDIT.
// Source: gin-vue-admin/internal/hmdr_api/service/v1 (interfaces: Factory,AgentInfoSrv,GroupSrv,HostSrv,WebServerLogWatcherSrv,WebServerStatisticsSrv)
//
// Generated by this command:
//
//	mockgen -self_package=gin-vue-admin/internal/hmdr_api/service/v1 -destination=mock_service.go -package=v1 gin-vue-admin/internal/hmdr_api/service/v1 Factory,AgentInfoSrv,GroupSrv,HostSrv,WebServerLogWatcherSrv,WebServerStatisticsSrv
//

// Package v1 is a generated GoMock package.
package v1

import (
	context "context"
	v1 "gin-vue-admin/api/heimdallr_api/v1"
	v11 "gin-vue-admin/internal/pkg/meta/v1"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockFactory is a mock of Factory interface.
type MockFactory struct {
	ctrl     *gomock.Controller
	recorder *MockFactoryMockRecorder
}

// MockFactoryMockRecorder is the mock recorder for MockFactory.
type MockFactoryMockRecorder struct {
	mock *MockFactory
}

// NewMockFactory creates a new mock instance.
func NewMockFactory(ctrl *gomock.Controller) *MockFactory {
	mock := &MockFactory{ctrl: ctrl}
	mock.recorder = &MockFactoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFactory) EXPECT() *MockFactoryMockRecorder {
	return m.recorder
}

// AgentInfos mocks base method.
func (m *MockFactory) AgentInfos() AgentInfoSrv {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AgentInfos")
	ret0, _ := ret[0].(AgentInfoSrv)
	return ret0
}

// AgentInfos indicates an expected call of AgentInfos.
func (mr *MockFactoryMockRecorder) AgentInfos() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AgentInfos", reflect.TypeOf((*MockFactory)(nil).AgentInfos))
}

// Groups mocks base method.
func (m *MockFactory) Groups() GroupSrv {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Groups")
	ret0, _ := ret[0].(GroupSrv)
	return ret0
}

// Groups indicates an expected call of Groups.
func (mr *MockFactoryMockRecorder) Groups() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Groups", reflect.TypeOf((*MockFactory)(nil).Groups))
}

// Hosts mocks base method.
func (m *MockFactory) Hosts() HostSrv {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Hosts")
	ret0, _ := ret[0].(HostSrv)
	return ret0
}

// Hosts indicates an expected call of Hosts.
func (mr *MockFactoryMockRecorder) Hosts() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Hosts", reflect.TypeOf((*MockFactory)(nil).Hosts))
}

// WebServerConfigs mocks base method.
func (m *MockFactory) WebServerConfigs() WebServerConfigSrv {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WebServerConfigs")
	ret0, _ := ret[0].(WebServerConfigSrv)
	return ret0
}

// WebServerConfigs indicates an expected call of WebServerConfigs.
func (mr *MockFactoryMockRecorder) WebServerConfigs() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WebServerConfigs", reflect.TypeOf((*MockFactory)(nil).WebServerConfigs))
}

// WebServerLogWatchers mocks base method.
func (m *MockFactory) WebServerLogWatchers() WebServerLogWatcherSrv {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WebServerLogWatchers")
	ret0, _ := ret[0].(WebServerLogWatcherSrv)
	return ret0
}

// WebServerLogWatchers indicates an expected call of WebServerLogWatchers.
func (mr *MockFactoryMockRecorder) WebServerLogWatchers() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WebServerLogWatchers", reflect.TypeOf((*MockFactory)(nil).WebServerLogWatchers))
}

// WebServerStatistics mocks base method.
func (m *MockFactory) WebServerStatistics() WebServerStatisticsSrv {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WebServerStatistics")
	ret0, _ := ret[0].(WebServerStatisticsSrv)
	return ret0
}

// WebServerStatistics indicates an expected call of WebServerStatistics.
func (mr *MockFactoryMockRecorder) WebServerStatistics() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WebServerStatistics", reflect.TypeOf((*MockFactory)(nil).WebServerStatistics))
}

// MockAgentInfoSrv is a mock of AgentInfoSrv interface.
type MockAgentInfoSrv struct {
	ctrl     *gomock.Controller
	recorder *MockAgentInfoSrvMockRecorder
}

// MockAgentInfoSrvMockRecorder is the mock recorder for MockAgentInfoSrv.
type MockAgentInfoSrvMockRecorder struct {
	mock *MockAgentInfoSrv
}

// NewMockAgentInfoSrv creates a new mock instance.
func NewMockAgentInfoSrv(ctrl *gomock.Controller) *MockAgentInfoSrv {
	mock := &MockAgentInfoSrv{ctrl: ctrl}
	mock.recorder = &MockAgentInfoSrvMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAgentInfoSrv) EXPECT() *MockAgentInfoSrvMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockAgentInfoSrv) Get(arg0 context.Context) ([]v1.GroupInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0)
	ret0, _ := ret[0].([]v1.GroupInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockAgentInfoSrvMockRecorder) Get(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockAgentInfoSrv)(nil).Get), arg0)
}

// MockGroupSrv is a mock of GroupSrv interface.
type MockGroupSrv struct {
	ctrl     *gomock.Controller
	recorder *MockGroupSrvMockRecorder
}

// MockGroupSrvMockRecorder is the mock recorder for MockGroupSrv.
type MockGroupSrvMockRecorder struct {
	mock *MockGroupSrv
}

// NewMockGroupSrv creates a new mock instance.
func NewMockGroupSrv(ctrl *gomock.Controller) *MockGroupSrv {
	mock := &MockGroupSrv{ctrl: ctrl}
	mock.recorder = &MockGroupSrvMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGroupSrv) EXPECT() *MockGroupSrvMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockGroupSrv) Create(arg0 context.Context, arg1 v1.Group) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockGroupSrvMockRecorder) Create(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockGroupSrv)(nil).Create), arg0, arg1)
}

// Delete mocks base method.
func (m *MockGroupSrv) Delete(arg0 context.Context, arg1 uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockGroupSrvMockRecorder) Delete(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockGroupSrv)(nil).Delete), arg0, arg1)
}

// DeleteCollections mocks base method.
func (m *MockGroupSrv) DeleteCollections(arg0 context.Context, arg1 v11.IDsOptions) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCollections", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteCollections indicates an expected call of DeleteCollections.
func (mr *MockGroupSrvMockRecorder) DeleteCollections(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCollections", reflect.TypeOf((*MockGroupSrv)(nil).DeleteCollections), arg0, arg1)
}

// Get mocks base method.
func (m *MockGroupSrv) Get(arg0 context.Context, arg1 uint) (v1.Group, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0, arg1)
	ret0, _ := ret[0].(v1.Group)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockGroupSrvMockRecorder) Get(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockGroupSrv)(nil).Get), arg0, arg1)
}

// List mocks base method.
func (m *MockGroupSrv) List(arg0 context.Context, arg1 v11.ListOptions) (v1.GroupList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", arg0, arg1)
	ret0, _ := ret[0].(v1.GroupList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockGroupSrvMockRecorder) List(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockGroupSrv)(nil).List), arg0, arg1)
}

// Update mocks base method.
func (m *MockGroupSrv) Update(arg0 context.Context, arg1 v1.Group) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockGroupSrvMockRecorder) Update(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockGroupSrv)(nil).Update), arg0, arg1)
}

// MockHostSrv is a mock of HostSrv interface.
type MockHostSrv struct {
	ctrl     *gomock.Controller
	recorder *MockHostSrvMockRecorder
}

// MockHostSrvMockRecorder is the mock recorder for MockHostSrv.
type MockHostSrvMockRecorder struct {
	mock *MockHostSrv
}

// NewMockHostSrv creates a new mock instance.
func NewMockHostSrv(ctrl *gomock.Controller) *MockHostSrv {
	mock := &MockHostSrv{ctrl: ctrl}
	mock.recorder = &MockHostSrvMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHostSrv) EXPECT() *MockHostSrvMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockHostSrv) Create(arg0 context.Context, arg1 v1.Host) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockHostSrvMockRecorder) Create(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockHostSrv)(nil).Create), arg0, arg1)
}

// Delete mocks base method.
func (m *MockHostSrv) Delete(arg0 context.Context, arg1 uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockHostSrvMockRecorder) Delete(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockHostSrv)(nil).Delete), arg0, arg1)
}

// DeleteCollection mocks base method.
func (m *MockHostSrv) DeleteCollection(arg0 context.Context, arg1 v11.IDsOptions) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCollection", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteCollection indicates an expected call of DeleteCollection.
func (mr *MockHostSrvMockRecorder) DeleteCollection(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCollection", reflect.TypeOf((*MockHostSrv)(nil).DeleteCollection), arg0, arg1)
}

// Get mocks base method.
func (m *MockHostSrv) Get(arg0 context.Context, arg1 uint) (v1.Host, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0, arg1)
	ret0, _ := ret[0].(v1.Host)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockHostSrvMockRecorder) Get(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockHostSrv)(nil).Get), arg0, arg1)
}

// List mocks base method.
func (m *MockHostSrv) List(arg0 context.Context, arg1 v11.ListOptions) (v1.HostList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", arg0, arg1)
	ret0, _ := ret[0].(v1.HostList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockHostSrvMockRecorder) List(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockHostSrv)(nil).List), arg0, arg1)
}

// Update mocks base method.
func (m *MockHostSrv) Update(arg0 context.Context, arg1 v1.Host) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockHostSrvMockRecorder) Update(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockHostSrv)(nil).Update), arg0, arg1)
}

// MockWebServerLogWatcherSrv is a mock of WebServerLogWatcherSrv interface.
type MockWebServerLogWatcherSrv struct {
	ctrl     *gomock.Controller
	recorder *MockWebServerLogWatcherSrvMockRecorder
}

// MockWebServerLogWatcherSrvMockRecorder is the mock recorder for MockWebServerLogWatcherSrv.
type MockWebServerLogWatcherSrvMockRecorder struct {
	mock *MockWebServerLogWatcherSrv
}

// NewMockWebServerLogWatcherSrv creates a new mock instance.
func NewMockWebServerLogWatcherSrv(ctrl *gomock.Controller) *MockWebServerLogWatcherSrv {
	mock := &MockWebServerLogWatcherSrv{ctrl: ctrl}
	mock.recorder = &MockWebServerLogWatcherSrvMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWebServerLogWatcherSrv) EXPECT() *MockWebServerLogWatcherSrvMockRecorder {
	return m.recorder
}

// Watch mocks base method.
func (m *MockWebServerLogWatcherSrv) Watch(arg0 context.Context, arg1 v11.WebServerLogOptions) (<-chan []byte, context.CancelFunc, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Watch", arg0, arg1)
	ret0, _ := ret[0].(<-chan []byte)
	ret1, _ := ret[1].(context.CancelFunc)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Watch indicates an expected call of Watch.
func (mr *MockWebServerLogWatcherSrvMockRecorder) Watch(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Watch", reflect.TypeOf((*MockWebServerLogWatcherSrv)(nil).Watch), arg0, arg1)
}

// MockWebServerStatisticsSrv is a mock of WebServerStatisticsSrv interface.
type MockWebServerStatisticsSrv struct {
	ctrl     *gomock.Controller
	recorder *MockWebServerStatisticsSrvMockRecorder
}

// MockWebServerStatisticsSrvMockRecorder is the mock recorder for MockWebServerStatisticsSrv.
type MockWebServerStatisticsSrvMockRecorder struct {
	mock *MockWebServerStatisticsSrv
}

// NewMockWebServerStatisticsSrv creates a new mock instance.
func NewMockWebServerStatisticsSrv(ctrl *gomock.Controller) *MockWebServerStatisticsSrv {
	mock := &MockWebServerStatisticsSrv{ctrl: ctrl}
	mock.recorder = &MockWebServerStatisticsSrvMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWebServerStatisticsSrv) EXPECT() *MockWebServerStatisticsSrvMockRecorder {
	return m.recorder
}

// GetProxyServiceInfo mocks base method.
func (m *MockWebServerStatisticsSrv) GetProxyServiceInfo(arg0 context.Context, arg1 v11.WebServerOptions) ([]v1.ProxyServiceInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProxyServiceInfo", arg0, arg1)
	ret0, _ := ret[0].([]v1.ProxyServiceInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProxyServiceInfo indicates an expected call of GetProxyServiceInfo.
func (mr *MockWebServerStatisticsSrvMockRecorder) GetProxyServiceInfo(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProxyServiceInfo", reflect.TypeOf((*MockWebServerStatisticsSrv)(nil).GetProxyServiceInfo), arg0, arg1)
}
