// Code generated by MockGen. DO NOT EDIT.
// Source: gin-vue-admin/pkg/sort_map (interfaces: SortMap,MapIndexes,Keyer)
//
// Generated by this command:
//
//	mockgen -self_package=gin-vue-admin/pkg/sort_map -destination=mock_sort_map.go -package=sort_map gin-vue-admin/pkg/sort_map SortMap,MapIndexes,Keyer
//

// Package sort_map is a generated GoMock package.
package sort_map

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockSortMap is a mock of SortMap interface.
type MockSortMap struct {
	ctrl     *gomock.Controller
	recorder *MockSortMapMockRecorder
	isgomock struct{}
}

// MockSortMapMockRecorder is the mock recorder for MockSortMap.
type MockSortMapMockRecorder struct {
	mock *MockSortMap
}

// NewMockSortMap creates a new mock instance.
func NewMockSortMap(ctrl *gomock.Controller) *MockSortMap {
	mock := &MockSortMap{ctrl: ctrl}
	mock.recorder = &MockSortMapMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSortMap) EXPECT() *MockSortMapMockRecorder {
	return m.recorder
}

// GetByKey mocks base method.
func (m *MockSortMap) GetByKey(key any) (any, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByKey", key)
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// GetByKey indicates an expected call of GetByKey.
func (mr *MockSortMapMockRecorder) GetByKey(key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByKey", reflect.TypeOf((*MockSortMap)(nil).GetByKey), key)
}

// Insert mocks base method.
func (m *MockSortMap) Insert(keyer Keyer, v any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Insert", keyer, v)
	ret0, _ := ret[0].(error)
	return ret0
}

// Insert indicates an expected call of Insert.
func (mr *MockSortMapMockRecorder) Insert(keyer, v any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockSortMap)(nil).Insert), keyer, v)
}

// Range mocks base method.
func (m *MockSortMap) Range(arg0 func(Keyer, any) bool) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Range", arg0)
}

// Range indicates an expected call of Range.
func (mr *MockSortMapMockRecorder) Range(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Range", reflect.TypeOf((*MockSortMap)(nil).Range), arg0)
}

// RemoveByKey mocks base method.
func (m *MockSortMap) RemoveByKey(key any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveByKey", key)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveByKey indicates an expected call of RemoveByKey.
func (mr *MockSortMapMockRecorder) RemoveByKey(key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveByKey", reflect.TypeOf((*MockSortMap)(nil).RemoveByKey), key)
}

// MockMapIndexes is a mock of MapIndexes interface.
type MockMapIndexes struct {
	ctrl     *gomock.Controller
	recorder *MockMapIndexesMockRecorder
	isgomock struct{}
}

// MockMapIndexesMockRecorder is the mock recorder for MockMapIndexes.
type MockMapIndexesMockRecorder struct {
	mock *MockMapIndexes
}

// NewMockMapIndexes creates a new mock instance.
func NewMockMapIndexes(ctrl *gomock.Controller) *MockMapIndexes {
	mock := &MockMapIndexes{ctrl: ctrl}
	mock.recorder = &MockMapIndexesMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMapIndexes) EXPECT() *MockMapIndexesMockRecorder {
	return m.recorder
}

// Insert mocks base method.
func (m *MockMapIndexes) Insert(keyer Keyer) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Insert", keyer)
}

// Insert indicates an expected call of Insert.
func (mr *MockMapIndexesMockRecorder) Insert(keyer any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockMapIndexes)(nil).Insert), keyer)
}

// Range mocks base method.
func (m *MockMapIndexes) Range(arg0 func(int, Keyer) bool) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Range", arg0)
}

// Range indicates an expected call of Range.
func (mr *MockMapIndexesMockRecorder) Range(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Range", reflect.TypeOf((*MockMapIndexes)(nil).Range), arg0)
}

// Remove mocks base method.
func (m *MockMapIndexes) Remove(keyer Keyer) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Remove", keyer)
}

// Remove indicates an expected call of Remove.
func (mr *MockMapIndexesMockRecorder) Remove(keyer any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Remove", reflect.TypeOf((*MockMapIndexes)(nil).Remove), keyer)
}

// MockKeyer is a mock of Keyer interface.
type MockKeyer struct {
	ctrl     *gomock.Controller
	recorder *MockKeyerMockRecorder
	isgomock struct{}
}

// MockKeyerMockRecorder is the mock recorder for MockKeyer.
type MockKeyerMockRecorder struct {
	mock *MockKeyer
}

// NewMockKeyer creates a new mock instance.
func NewMockKeyer(ctrl *gomock.Controller) *MockKeyer {
	mock := &MockKeyer{ctrl: ctrl}
	mock.recorder = &MockKeyerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockKeyer) EXPECT() *MockKeyerMockRecorder {
	return m.recorder
}

// GetOrder mocks base method.
func (m *MockKeyer) GetOrder() uint {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrder")
	ret0, _ := ret[0].(uint)
	return ret0
}

// GetOrder indicates an expected call of GetOrder.
func (mr *MockKeyerMockRecorder) GetOrder() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrder", reflect.TypeOf((*MockKeyer)(nil).GetOrder))
}

// Key mocks base method.
func (m *MockKeyer) Key() any {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Key")
	ret0, _ := ret[0].(any)
	return ret0
}

// Key indicates an expected call of Key.
func (mr *MockKeyerMockRecorder) Key() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Key", reflect.TypeOf((*MockKeyer)(nil).Key))
}
