// Code generated by MockGen. DO NOT EDIT.
// Source: gin-vue-admin/pkg/client/v1/endpoint (interfaces: Factory,AgentInfoEndpoints,GroupEndpoints,HostEndpoints,WebServerConfigEndpoints,WebServerBinCMDEndpoints,WebServerStatisticsEndpoints)
//
// Generated by this command:
//
//	mockgen -self_package=gin-vue-admin/pkg/client/v1/endpoint -destination=mock_endpoint.go -package=endpoint gin-vue-admin/pkg/client/v1/endpoint Factory,AgentInfoEndpoints,GroupEndpoints,HostEndpoints,WebServerConfigEndpoints,WebServerBinCMDEndpoints,WebServerStatisticsEndpoints
//

// Package endpoint is a generated GoMock package.
package endpoint

import (
	v1 "gin-vue-admin/api/heimdallr_api/v1"
	v10 "gin-vue-admin/internal/pkg/meta/v1"
	model "gin-vue-admin/pkg/client/v1/model"
	reflect "reflect"

	v11 "github.com/ClessLi/component-base/pkg/client-sdk/http/v1"
	gomock "go.uber.org/mock/gomock"
)

// MockFactory is a mock of Factory interface.
type MockFactory struct {
	ctrl     *gomock.Controller
	recorder *MockFactoryMockRecorder
	isgomock struct{}
}

// MockFactoryMockRecorder is the mock recorder for MockFactory.
type MockFactoryMockRecorder struct {
	mock *MockFactory
}

// NewMockFactory creates a new mock instance.
func NewMockFactory(ctrl *gomock.Controller) *MockFactory {
	mock := &MockFactory{ctrl: ctrl}
	mock.recorder = &MockFactoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFactory) EXPECT() *MockFactoryMockRecorder {
	return m.recorder
}

// AgentInfos mocks base method.
func (m *MockFactory) AgentInfos() AgentInfoEndpoints {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AgentInfos")
	ret0, _ := ret[0].(AgentInfoEndpoints)
	return ret0
}

// AgentInfos indicates an expected call of AgentInfos.
func (mr *MockFactoryMockRecorder) AgentInfos() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AgentInfos", reflect.TypeOf((*MockFactory)(nil).AgentInfos))
}

// Groups mocks base method.
func (m *MockFactory) Groups() GroupEndpoints {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Groups")
	ret0, _ := ret[0].(GroupEndpoints)
	return ret0
}

// Groups indicates an expected call of Groups.
func (mr *MockFactoryMockRecorder) Groups() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Groups", reflect.TypeOf((*MockFactory)(nil).Groups))
}

// Hosts mocks base method.
func (m *MockFactory) Hosts() HostEndpoints {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Hosts")
	ret0, _ := ret[0].(HostEndpoints)
	return ret0
}

// Hosts indicates an expected call of Hosts.
func (mr *MockFactoryMockRecorder) Hosts() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Hosts", reflect.TypeOf((*MockFactory)(nil).Hosts))
}

// WebServerBinCMDs mocks base method.
func (m *MockFactory) WebServerBinCMDs() WebServerBinCMDEndpoints {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WebServerBinCMDs")
	ret0, _ := ret[0].(WebServerBinCMDEndpoints)
	return ret0
}

// WebServerBinCMDs indicates an expected call of WebServerBinCMDs.
func (mr *MockFactoryMockRecorder) WebServerBinCMDs() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WebServerBinCMDs", reflect.TypeOf((*MockFactory)(nil).WebServerBinCMDs))
}

// WebServerConfigs mocks base method.
func (m *MockFactory) WebServerConfigs() WebServerConfigEndpoints {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WebServerConfigs")
	ret0, _ := ret[0].(WebServerConfigEndpoints)
	return ret0
}

// WebServerConfigs indicates an expected call of WebServerConfigs.
func (mr *MockFactoryMockRecorder) WebServerConfigs() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WebServerConfigs", reflect.TypeOf((*MockFactory)(nil).WebServerConfigs))
}

// WebServerStatistics mocks base method.
func (m *MockFactory) WebServerStatistics() WebServerStatisticsEndpoints {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WebServerStatistics")
	ret0, _ := ret[0].(WebServerStatisticsEndpoints)
	return ret0
}

// WebServerStatistics indicates an expected call of WebServerStatistics.
func (mr *MockFactoryMockRecorder) WebServerStatistics() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WebServerStatistics", reflect.TypeOf((*MockFactory)(nil).WebServerStatistics))
}

// MockAgentInfoEndpoints is a mock of AgentInfoEndpoints interface.
type MockAgentInfoEndpoints struct {
	ctrl     *gomock.Controller
	recorder *MockAgentInfoEndpointsMockRecorder
	isgomock struct{}
}

// MockAgentInfoEndpointsMockRecorder is the mock recorder for MockAgentInfoEndpoints.
type MockAgentInfoEndpointsMockRecorder struct {
	mock *MockAgentInfoEndpoints
}

// NewMockAgentInfoEndpoints creates a new mock instance.
func NewMockAgentInfoEndpoints(ctrl *gomock.Controller) *MockAgentInfoEndpoints {
	mock := &MockAgentInfoEndpoints{ctrl: ctrl}
	mock.recorder = &MockAgentInfoEndpointsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAgentInfoEndpoints) EXPECT() *MockAgentInfoEndpointsMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockAgentInfoEndpoints) Get() v11.Endpoint[v11.NilBody, model.ResponseBody[[]v1.GroupInfo]] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get")
	ret0, _ := ret[0].(v11.Endpoint[v11.NilBody, model.ResponseBody[[]v1.GroupInfo]])
	return ret0
}

// Get indicates an expected call of Get.
func (mr *MockAgentInfoEndpointsMockRecorder) Get() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockAgentInfoEndpoints)(nil).Get))
}

// MockGroupEndpoints is a mock of GroupEndpoints interface.
type MockGroupEndpoints struct {
	ctrl     *gomock.Controller
	recorder *MockGroupEndpointsMockRecorder
	isgomock struct{}
}

// MockGroupEndpointsMockRecorder is the mock recorder for MockGroupEndpoints.
type MockGroupEndpointsMockRecorder struct {
	mock *MockGroupEndpoints
}

// NewMockGroupEndpoints creates a new mock instance.
func NewMockGroupEndpoints(ctrl *gomock.Controller) *MockGroupEndpoints {
	mock := &MockGroupEndpoints{ctrl: ctrl}
	mock.recorder = &MockGroupEndpointsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGroupEndpoints) EXPECT() *MockGroupEndpointsMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockGroupEndpoints) Get() v11.Endpoint[v10.IDOptions, model.ResponseBody[*v1.Group]] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get")
	ret0, _ := ret[0].(v11.Endpoint[v10.IDOptions, model.ResponseBody[*v1.Group]])
	return ret0
}

// Get indicates an expected call of Get.
func (mr *MockGroupEndpointsMockRecorder) Get() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockGroupEndpoints)(nil).Get))
}

// List mocks base method.
func (m *MockGroupEndpoints) List() v11.Endpoint[v10.ListOptions, model.ResponseBody[*v1.GroupList]] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List")
	ret0, _ := ret[0].(v11.Endpoint[v10.ListOptions, model.ResponseBody[*v1.GroupList]])
	return ret0
}

// List indicates an expected call of List.
func (mr *MockGroupEndpointsMockRecorder) List() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockGroupEndpoints)(nil).List))
}

// MockHostEndpoints is a mock of HostEndpoints interface.
type MockHostEndpoints struct {
	ctrl     *gomock.Controller
	recorder *MockHostEndpointsMockRecorder
	isgomock struct{}
}

// MockHostEndpointsMockRecorder is the mock recorder for MockHostEndpoints.
type MockHostEndpointsMockRecorder struct {
	mock *MockHostEndpoints
}

// NewMockHostEndpoints creates a new mock instance.
func NewMockHostEndpoints(ctrl *gomock.Controller) *MockHostEndpoints {
	mock := &MockHostEndpoints{ctrl: ctrl}
	mock.recorder = &MockHostEndpointsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHostEndpoints) EXPECT() *MockHostEndpointsMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockHostEndpoints) Get() v11.Endpoint[v10.IDOptions, model.ResponseBody[*v1.Host]] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get")
	ret0, _ := ret[0].(v11.Endpoint[v10.IDOptions, model.ResponseBody[*v1.Host]])
	return ret0
}

// Get indicates an expected call of Get.
func (mr *MockHostEndpointsMockRecorder) Get() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockHostEndpoints)(nil).Get))
}

// List mocks base method.
func (m *MockHostEndpoints) List() v11.Endpoint[v10.ListOptions, model.ResponseBody[*v1.HostList]] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List")
	ret0, _ := ret[0].(v11.Endpoint[v10.ListOptions, model.ResponseBody[*v1.HostList]])
	return ret0
}

// List indicates an expected call of List.
func (mr *MockHostEndpointsMockRecorder) List() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockHostEndpoints)(nil).List))
}

// MockWebServerConfigEndpoints is a mock of WebServerConfigEndpoints interface.
type MockWebServerConfigEndpoints struct {
	ctrl     *gomock.Controller
	recorder *MockWebServerConfigEndpointsMockRecorder
	isgomock struct{}
}

// MockWebServerConfigEndpointsMockRecorder is the mock recorder for MockWebServerConfigEndpoints.
type MockWebServerConfigEndpointsMockRecorder struct {
	mock *MockWebServerConfigEndpoints
}

// NewMockWebServerConfigEndpoints creates a new mock instance.
func NewMockWebServerConfigEndpoints(ctrl *gomock.Controller) *MockWebServerConfigEndpoints {
	mock := &MockWebServerConfigEndpoints{ctrl: ctrl}
	mock.recorder = &MockWebServerConfigEndpointsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWebServerConfigEndpoints) EXPECT() *MockWebServerConfigEndpointsMockRecorder {
	return m.recorder
}

// ChangeContextEnabledState mocks base method.
func (m *MockWebServerConfigEndpoints) ChangeContextEnabledState() v11.Endpoint[v10.WebServerConfigContextUpdateOptions[v10.ConfigContextEnabledStateMeta], model.ResponseBody[v11.NilBody]] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChangeContextEnabledState")
	ret0, _ := ret[0].(v11.Endpoint[v10.WebServerConfigContextUpdateOptions[v10.ConfigContextEnabledStateMeta], model.ResponseBody[v11.NilBody]])
	return ret0
}

// ChangeContextEnabledState indicates an expected call of ChangeContextEnabledState.
func (mr *MockWebServerConfigEndpointsMockRecorder) ChangeContextEnabledState() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChangeContextEnabledState", reflect.TypeOf((*MockWebServerConfigEndpoints)(nil).ChangeContextEnabledState))
}

// GetConfig mocks base method.
func (m *MockWebServerConfigEndpoints) GetConfig() v11.Endpoint[v10.WebServerOptions, model.ResponseBody[*model.WebServerConfig]] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConfig")
	ret0, _ := ret[0].(v11.Endpoint[v10.WebServerOptions, model.ResponseBody[*model.WebServerConfig]])
	return ret0
}

// GetConfig indicates an expected call of GetConfig.
func (mr *MockWebServerConfigEndpointsMockRecorder) GetConfig() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConfig", reflect.TypeOf((*MockWebServerConfigEndpoints)(nil).GetConfig))
}

// GetConfigTextLines mocks base method.
func (m *MockWebServerConfigEndpoints) GetConfigTextLines() v11.Endpoint[v10.WebServerOptions, model.ResponseBody[string]] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConfigTextLines")
	ret0, _ := ret[0].(v11.Endpoint[v10.WebServerOptions, model.ResponseBody[string]])
	return ret0
}

// GetConfigTextLines indicates an expected call of GetConfigTextLines.
func (mr *MockWebServerConfigEndpointsMockRecorder) GetConfigTextLines() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConfigTextLines", reflect.TypeOf((*MockWebServerConfigEndpoints)(nil).GetConfigTextLines))
}

// GetContextTextLines mocks base method.
func (m *MockWebServerConfigEndpoints) GetContextTextLines() v11.Endpoint[v10.WebServerConfigTargetContextOptions, model.ResponseBody[string]] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetContextTextLines")
	ret0, _ := ret[0].(v11.Endpoint[v10.WebServerConfigTargetContextOptions, model.ResponseBody[string]])
	return ret0
}

// GetContextTextLines indicates an expected call of GetContextTextLines.
func (mr *MockWebServerConfigEndpointsMockRecorder) GetContextTextLines() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetContextTextLines", reflect.TypeOf((*MockWebServerConfigEndpoints)(nil).GetContextTextLines))
}

// GetIncludedConfigs mocks base method.
func (m *MockWebServerConfigEndpoints) GetIncludedConfigs() v11.Endpoint[v10.WebServerConfigTargetContextOptions, model.ResponseBody[[]string]] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIncludedConfigs")
	ret0, _ := ret[0].(v11.Endpoint[v10.WebServerConfigTargetContextOptions, model.ResponseBody[[]string]])
	return ret0
}

// GetIncludedConfigs indicates an expected call of GetIncludedConfigs.
func (mr *MockWebServerConfigEndpointsMockRecorder) GetIncludedConfigs() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIncludedConfigs", reflect.TypeOf((*MockWebServerConfigEndpoints)(nil).GetIncludedConfigs))
}

// GetOptions mocks base method.
func (m *MockWebServerConfigEndpoints) GetOptions() v11.Endpoint[v11.NilBody, model.ResponseBody[[]v1.BifrostGroupMeta]] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOptions")
	ret0, _ := ret[0].(v11.Endpoint[v11.NilBody, model.ResponseBody[[]v1.BifrostGroupMeta]])
	return ret0
}

// GetOptions indicates an expected call of GetOptions.
func (mr *MockWebServerConfigEndpointsMockRecorder) GetOptions() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOptions", reflect.TypeOf((*MockWebServerConfigEndpoints)(nil).GetOptions))
}

// InsertWithClone mocks base method.
func (m *MockWebServerConfigEndpoints) InsertWithClone() v11.Endpoint[v10.WebServerConfigContextUpdateOptions[v10.CloneConfigContextMeta], model.ResponseBody[v11.NilBody]] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertWithClone")
	ret0, _ := ret[0].(v11.Endpoint[v10.WebServerConfigContextUpdateOptions[v10.CloneConfigContextMeta], model.ResponseBody[v11.NilBody]])
	return ret0
}

// InsertWithClone indicates an expected call of InsertWithClone.
func (mr *MockWebServerConfigEndpointsMockRecorder) InsertWithClone() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertWithClone", reflect.TypeOf((*MockWebServerConfigEndpoints)(nil).InsertWithClone))
}

// InsertWithNew mocks base method.
func (m *MockWebServerConfigEndpoints) InsertWithNew() v11.Endpoint[v10.WebServerConfigContextUpdateOptions[v10.NewConfigContextMeta], model.ResponseBody[v11.NilBody]] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertWithNew")
	ret0, _ := ret[0].(v11.Endpoint[v10.WebServerConfigContextUpdateOptions[v10.NewConfigContextMeta], model.ResponseBody[v11.NilBody]])
	return ret0
}

// InsertWithNew indicates an expected call of InsertWithNew.
func (mr *MockWebServerConfigEndpointsMockRecorder) InsertWithNew() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertWithNew", reflect.TypeOf((*MockWebServerConfigEndpoints)(nil).InsertWithNew))
}

// ModifyContextValue mocks base method.
func (m *MockWebServerConfigEndpoints) ModifyContextValue() v11.Endpoint[v10.WebServerConfigContextUpdateOptions[v10.NewConfigContextMeta], model.ResponseBody[v11.NilBody]] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ModifyContextValue")
	ret0, _ := ret[0].(v11.Endpoint[v10.WebServerConfigContextUpdateOptions[v10.NewConfigContextMeta], model.ResponseBody[v11.NilBody]])
	return ret0
}

// ModifyContextValue indicates an expected call of ModifyContextValue.
func (mr *MockWebServerConfigEndpointsMockRecorder) ModifyContextValue() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ModifyContextValue", reflect.TypeOf((*MockWebServerConfigEndpoints)(nil).ModifyContextValue))
}

// ModifyWithClone mocks base method.
func (m *MockWebServerConfigEndpoints) ModifyWithClone() v11.Endpoint[v10.WebServerConfigContextUpdateOptions[v10.CloneConfigContextMeta], model.ResponseBody[v11.NilBody]] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ModifyWithClone")
	ret0, _ := ret[0].(v11.Endpoint[v10.WebServerConfigContextUpdateOptions[v10.CloneConfigContextMeta], model.ResponseBody[v11.NilBody]])
	return ret0
}

// ModifyWithClone indicates an expected call of ModifyWithClone.
func (mr *MockWebServerConfigEndpointsMockRecorder) ModifyWithClone() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ModifyWithClone", reflect.TypeOf((*MockWebServerConfigEndpoints)(nil).ModifyWithClone))
}

// ModifyWithNew mocks base method.
func (m *MockWebServerConfigEndpoints) ModifyWithNew() v11.Endpoint[v10.WebServerConfigContextUpdateOptions[v10.NewConfigContextMeta], model.ResponseBody[v11.NilBody]] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ModifyWithNew")
	ret0, _ := ret[0].(v11.Endpoint[v10.WebServerConfigContextUpdateOptions[v10.NewConfigContextMeta], model.ResponseBody[v11.NilBody]])
	return ret0
}

// ModifyWithNew indicates an expected call of ModifyWithNew.
func (mr *MockWebServerConfigEndpointsMockRecorder) ModifyWithNew() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ModifyWithNew", reflect.TypeOf((*MockWebServerConfigEndpoints)(nil).ModifyWithNew))
}

// Move mocks base method.
func (m *MockWebServerConfigEndpoints) Move() v11.Endpoint[v10.WebServerConfigContextUpdateOptions[v10.CloneConfigContextMeta], model.ResponseBody[v11.NilBody]] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Move")
	ret0, _ := ret[0].(v11.Endpoint[v10.WebServerConfigContextUpdateOptions[v10.CloneConfigContextMeta], model.ResponseBody[v11.NilBody]])
	return ret0
}

// Move indicates an expected call of Move.
func (mr *MockWebServerConfigEndpointsMockRecorder) Move() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Move", reflect.TypeOf((*MockWebServerConfigEndpoints)(nil).Move))
}

// Remove mocks base method.
func (m *MockWebServerConfigEndpoints) Remove() v11.Endpoint[v10.WebServerConfigTargetContextOptions, model.ResponseBody[v11.NilBody]] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Remove")
	ret0, _ := ret[0].(v11.Endpoint[v10.WebServerConfigTargetContextOptions, model.ResponseBody[v11.NilBody]])
	return ret0
}

// Remove indicates an expected call of Remove.
func (mr *MockWebServerConfigEndpointsMockRecorder) Remove() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Remove", reflect.TypeOf((*MockWebServerConfigEndpoints)(nil).Remove))
}

// SearchContextPositions mocks base method.
func (m *MockWebServerConfigEndpoints) SearchContextPositions() v11.Endpoint[v10.WebServerConfigContextPosSearchOptions, model.ResponseBody[[]v10.ConfigContextPos]] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchContextPositions")
	ret0, _ := ret[0].(v11.Endpoint[v10.WebServerConfigContextPosSearchOptions, model.ResponseBody[[]v10.ConfigContextPos]])
	return ret0
}

// SearchContextPositions indicates an expected call of SearchContextPositions.
func (mr *MockWebServerConfigEndpointsMockRecorder) SearchContextPositions() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchContextPositions", reflect.TypeOf((*MockWebServerConfigEndpoints)(nil).SearchContextPositions))
}

// UpdateConfig mocks base method.
func (m *MockWebServerConfigEndpoints) UpdateConfig() v11.Endpoint[*v10.WebServerConfigUpdateOptions, model.ResponseBody[v11.NilBody]] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateConfig")
	ret0, _ := ret[0].(v11.Endpoint[*v10.WebServerConfigUpdateOptions, model.ResponseBody[v11.NilBody]])
	return ret0
}

// UpdateConfig indicates an expected call of UpdateConfig.
func (mr *MockWebServerConfigEndpointsMockRecorder) UpdateConfig() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateConfig", reflect.TypeOf((*MockWebServerConfigEndpoints)(nil).UpdateConfig))
}

// MockWebServerBinCMDEndpoints is a mock of WebServerBinCMDEndpoints interface.
type MockWebServerBinCMDEndpoints struct {
	ctrl     *gomock.Controller
	recorder *MockWebServerBinCMDEndpointsMockRecorder
	isgomock struct{}
}

// MockWebServerBinCMDEndpointsMockRecorder is the mock recorder for MockWebServerBinCMDEndpoints.
type MockWebServerBinCMDEndpointsMockRecorder struct {
	mock *MockWebServerBinCMDEndpoints
}

// NewMockWebServerBinCMDEndpoints creates a new mock instance.
func NewMockWebServerBinCMDEndpoints(ctrl *gomock.Controller) *MockWebServerBinCMDEndpoints {
	mock := &MockWebServerBinCMDEndpoints{ctrl: ctrl}
	mock.recorder = &MockWebServerBinCMDEndpointsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWebServerBinCMDEndpoints) EXPECT() *MockWebServerBinCMDEndpointsMockRecorder {
	return m.recorder
}

// Exec mocks base method.
func (m *MockWebServerBinCMDEndpoints) Exec() v11.Endpoint[v10.WebServerBinCMDExecRequest, model.ResponseBody[*v10.WebServerBinCMDExecResponse]] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Exec")
	ret0, _ := ret[0].(v11.Endpoint[v10.WebServerBinCMDExecRequest, model.ResponseBody[*v10.WebServerBinCMDExecResponse]])
	return ret0
}

// Exec indicates an expected call of Exec.
func (mr *MockWebServerBinCMDEndpointsMockRecorder) Exec() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exec", reflect.TypeOf((*MockWebServerBinCMDEndpoints)(nil).Exec))
}

// MockWebServerStatisticsEndpoints is a mock of WebServerStatisticsEndpoints interface.
type MockWebServerStatisticsEndpoints struct {
	ctrl     *gomock.Controller
	recorder *MockWebServerStatisticsEndpointsMockRecorder
	isgomock struct{}
}

// MockWebServerStatisticsEndpointsMockRecorder is the mock recorder for MockWebServerStatisticsEndpoints.
type MockWebServerStatisticsEndpointsMockRecorder struct {
	mock *MockWebServerStatisticsEndpoints
}

// NewMockWebServerStatisticsEndpoints creates a new mock instance.
func NewMockWebServerStatisticsEndpoints(ctrl *gomock.Controller) *MockWebServerStatisticsEndpoints {
	mock := &MockWebServerStatisticsEndpoints{ctrl: ctrl}
	mock.recorder = &MockWebServerStatisticsEndpointsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWebServerStatisticsEndpoints) EXPECT() *MockWebServerStatisticsEndpointsMockRecorder {
	return m.recorder
}

// ConnectivityCheckOfProxyService mocks base method.
func (m *MockWebServerStatisticsEndpoints) ConnectivityCheckOfProxyService() v11.Endpoint[v10.ConnectivityCheckOfProxiedServersRequestOptions, model.ResponseBody[v1.ProxyServiceInfo]] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConnectivityCheckOfProxyService")
	ret0, _ := ret[0].(v11.Endpoint[v10.ConnectivityCheckOfProxiedServersRequestOptions, model.ResponseBody[v1.ProxyServiceInfo]])
	return ret0
}

// ConnectivityCheckOfProxyService indicates an expected call of ConnectivityCheckOfProxyService.
func (mr *MockWebServerStatisticsEndpointsMockRecorder) ConnectivityCheckOfProxyService() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConnectivityCheckOfProxyService", reflect.TypeOf((*MockWebServerStatisticsEndpoints)(nil).ConnectivityCheckOfProxyService))
}

// ExportProxyServiceInfoToExcel mocks base method.
func (m *MockWebServerStatisticsEndpoints) ExportProxyServiceInfoToExcel() v11.Endpoint[v10.WebServerOptions, model.ResponseBody[[]byte]] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExportProxyServiceInfoToExcel")
	ret0, _ := ret[0].(v11.Endpoint[v10.WebServerOptions, model.ResponseBody[[]byte]])
	return ret0
}

// ExportProxyServiceInfoToExcel indicates an expected call of ExportProxyServiceInfoToExcel.
func (mr *MockWebServerStatisticsEndpointsMockRecorder) ExportProxyServiceInfoToExcel() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExportProxyServiceInfoToExcel", reflect.TypeOf((*MockWebServerStatisticsEndpoints)(nil).ExportProxyServiceInfoToExcel))
}

// GetProxyServiceInfo mocks base method.
func (m *MockWebServerStatisticsEndpoints) GetProxyServiceInfo() v11.Endpoint[v10.WebServerOptions, model.ResponseBody[[]v1.ProxyServiceInfo]] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProxyServiceInfo")
	ret0, _ := ret[0].(v11.Endpoint[v10.WebServerOptions, model.ResponseBody[[]v1.ProxyServiceInfo]])
	return ret0
}

// GetProxyServiceInfo indicates an expected call of GetProxyServiceInfo.
func (mr *MockWebServerStatisticsEndpointsMockRecorder) GetProxyServiceInfo() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProxyServiceInfo", reflect.TypeOf((*MockWebServerStatisticsEndpoints)(nil).GetProxyServiceInfo))
}
