// Code generated by MockGen. DO NOT EDIT.
// Source: web_server_config.go
//
// Generated by this command:
//
//	mockgen -source=web_server_config.go -destination=generics_mock_web_server_config.go -package=v1 gin-vue-admin/internal/hmdr_api/store/v1 WebServerConfigStore
//

// Package v1 is a generated GoMock package.
package v1

import (
	context "context"
	v1 "gin-vue-admin/api/heimdallr_api/v1"
	v10 "gin-vue-admin/internal/pkg/meta/v1"
	reflect "reflect"

	configuration "github.com/ClessLi/bifrost/pkg/resolv/V3/nginx/configuration"
	context0 "github.com/ClessLi/bifrost/pkg/resolv/V3/nginx/configuration/context"
	utils "github.com/ClessLi/bifrost/pkg/resolv/V3/nginx/configuration/utils"
	gomock "go.uber.org/mock/gomock"
)

// MockWebServerConfigStore is a mock of WebServerConfigStore interface.
type MockWebServerConfigStore struct {
	ctrl     *gomock.Controller
	recorder *MockWebServerConfigStoreMockRecorder
}

// MockWebServerConfigStoreMockRecorder is the mock recorder for MockWebServerConfigStore.
type MockWebServerConfigStoreMockRecorder struct {
	mock *MockWebServerConfigStore
}

// NewMockWebServerConfigStore creates a new mock instance.
func NewMockWebServerConfigStore(ctrl *gomock.Controller) *MockWebServerConfigStore {
	mock := &MockWebServerConfigStore{ctrl: ctrl}
	mock.recorder = &MockWebServerConfigStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWebServerConfigStore) EXPECT() *MockWebServerConfigStoreMockRecorder {
	return m.recorder
}

// ChangeContextEnabledState mocks base method.
func (m *MockWebServerConfigStore) ChangeContextEnabledState(ctx context.Context, opts v10.WebServerOptions, ofp utils.ConfigFingerprints, ctxmeta v10.TargetConfigContextOptions[v10.ConfigContextEnabledStateMeta]) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChangeContextEnabledState", ctx, opts, ofp, ctxmeta)
	ret0, _ := ret[0].(error)
	return ret0
}

// ChangeContextEnabledState indicates an expected call of ChangeContextEnabledState.
func (mr *MockWebServerConfigStoreMockRecorder) ChangeContextEnabledState(ctx, opts, ofp, ctxmeta any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChangeContextEnabledState", reflect.TypeOf((*MockWebServerConfigStore)(nil).ChangeContextEnabledState), ctx, opts, ofp, ctxmeta)
}

// GetConfig mocks base method.
func (m *MockWebServerConfigStore) GetConfig(ctx context.Context, opts v10.WebServerOptions) (configuration.NginxConfig, utils.ConfigFingerprinter, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConfig", ctx, opts)
	ret0, _ := ret[0].(configuration.NginxConfig)
	ret1, _ := ret[1].(utils.ConfigFingerprinter)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetConfig indicates an expected call of GetConfig.
func (mr *MockWebServerConfigStoreMockRecorder) GetConfig(ctx, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConfig", reflect.TypeOf((*MockWebServerConfigStore)(nil).GetConfig), ctx, opts)
}

// GetContext mocks base method.
func (m *MockWebServerConfigStore) GetContext(ctx context.Context, opts v10.WebServerOptions, ofp utils.ConfigFingerprints, pos v10.ConfigContextPos) (context0.Context, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetContext", ctx, opts, ofp, pos)
	ret0, _ := ret[0].(context0.Context)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetContext indicates an expected call of GetContext.
func (mr *MockWebServerConfigStoreMockRecorder) GetContext(ctx, opts, ofp, pos any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetContext", reflect.TypeOf((*MockWebServerConfigStore)(nil).GetContext), ctx, opts, ofp, pos)
}

// GetIncludedConfigs mocks base method.
func (m *MockWebServerConfigStore) GetIncludedConfigs(ctx context.Context, opts v10.WebServerOptions, ofp utils.ConfigFingerprints, pos v10.ConfigContextPos) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIncludedConfigs", ctx, opts, ofp, pos)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetIncludedConfigs indicates an expected call of GetIncludedConfigs.
func (mr *MockWebServerConfigStoreMockRecorder) GetIncludedConfigs(ctx, opts, ofp, pos any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIncludedConfigs", reflect.TypeOf((*MockWebServerConfigStore)(nil).GetIncludedConfigs), ctx, opts, ofp, pos)
}

// GetOptions mocks base method.
func (m *MockWebServerConfigStore) GetOptions(ctx context.Context) ([]v1.BifrostGroupMeta, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOptions", ctx)
	ret0, _ := ret[0].([]v1.BifrostGroupMeta)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOptions indicates an expected call of GetOptions.
func (mr *MockWebServerConfigStoreMockRecorder) GetOptions(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOptions", reflect.TypeOf((*MockWebServerConfigStore)(nil).GetOptions), ctx)
}

// InsertWithClone mocks base method.
func (m *MockWebServerConfigStore) InsertWithClone(ctx context.Context, opts v10.WebServerOptions, ofp utils.ConfigFingerprints, ctxmeta v10.TargetConfigContextOptions[v10.CloneConfigContextMeta]) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertWithClone", ctx, opts, ofp, ctxmeta)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertWithClone indicates an expected call of InsertWithClone.
func (mr *MockWebServerConfigStoreMockRecorder) InsertWithClone(ctx, opts, ofp, ctxmeta any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertWithClone", reflect.TypeOf((*MockWebServerConfigStore)(nil).InsertWithClone), ctx, opts, ofp, ctxmeta)
}

// InsertWithNew mocks base method.
func (m *MockWebServerConfigStore) InsertWithNew(ctx context.Context, opts v10.WebServerOptions, ofp utils.ConfigFingerprints, ctxmeta v10.TargetConfigContextOptions[v10.NewConfigContextMeta]) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertWithNew", ctx, opts, ofp, ctxmeta)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertWithNew indicates an expected call of InsertWithNew.
func (mr *MockWebServerConfigStoreMockRecorder) InsertWithNew(ctx, opts, ofp, ctxmeta any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertWithNew", reflect.TypeOf((*MockWebServerConfigStore)(nil).InsertWithNew), ctx, opts, ofp, ctxmeta)
}

// ModifyContextValue mocks base method.
func (m *MockWebServerConfigStore) ModifyContextValue(ctx context.Context, opts v10.WebServerOptions, ofp utils.ConfigFingerprints, ctxmeta v10.TargetConfigContextOptions[v10.NewConfigContextMeta]) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ModifyContextValue", ctx, opts, ofp, ctxmeta)
	ret0, _ := ret[0].(error)
	return ret0
}

// ModifyContextValue indicates an expected call of ModifyContextValue.
func (mr *MockWebServerConfigStoreMockRecorder) ModifyContextValue(ctx, opts, ofp, ctxmeta any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ModifyContextValue", reflect.TypeOf((*MockWebServerConfigStore)(nil).ModifyContextValue), ctx, opts, ofp, ctxmeta)
}

// ModifyWithClone mocks base method.
func (m *MockWebServerConfigStore) ModifyWithClone(ctx context.Context, opts v10.WebServerOptions, ofp utils.ConfigFingerprints, ctxmeta v10.TargetConfigContextOptions[v10.CloneConfigContextMeta]) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ModifyWithClone", ctx, opts, ofp, ctxmeta)
	ret0, _ := ret[0].(error)
	return ret0
}

// ModifyWithClone indicates an expected call of ModifyWithClone.
func (mr *MockWebServerConfigStoreMockRecorder) ModifyWithClone(ctx, opts, ofp, ctxmeta any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ModifyWithClone", reflect.TypeOf((*MockWebServerConfigStore)(nil).ModifyWithClone), ctx, opts, ofp, ctxmeta)
}

// ModifyWithNew mocks base method.
func (m *MockWebServerConfigStore) ModifyWithNew(ctx context.Context, opts v10.WebServerOptions, ofp utils.ConfigFingerprints, ctxmeta v10.TargetConfigContextOptions[v10.NewConfigContextMeta]) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ModifyWithNew", ctx, opts, ofp, ctxmeta)
	ret0, _ := ret[0].(error)
	return ret0
}

// ModifyWithNew indicates an expected call of ModifyWithNew.
func (mr *MockWebServerConfigStoreMockRecorder) ModifyWithNew(ctx, opts, ofp, ctxmeta any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ModifyWithNew", reflect.TypeOf((*MockWebServerConfigStore)(nil).ModifyWithNew), ctx, opts, ofp, ctxmeta)
}

// Move mocks base method.
func (m *MockWebServerConfigStore) Move(ctx context.Context, opts v10.WebServerOptions, ofp utils.ConfigFingerprints, ctxmeta v10.TargetConfigContextOptions[v10.CloneConfigContextMeta]) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Move", ctx, opts, ofp, ctxmeta)
	ret0, _ := ret[0].(error)
	return ret0
}

// Move indicates an expected call of Move.
func (mr *MockWebServerConfigStoreMockRecorder) Move(ctx, opts, ofp, ctxmeta any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Move", reflect.TypeOf((*MockWebServerConfigStore)(nil).Move), ctx, opts, ofp, ctxmeta)
}

// Remove mocks base method.
func (m *MockWebServerConfigStore) Remove(ctx context.Context, opts v10.WebServerOptions, ofp utils.ConfigFingerprints, pos v10.ConfigContextPos) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Remove", ctx, opts, ofp, pos)
	ret0, _ := ret[0].(error)
	return ret0
}

// Remove indicates an expected call of Remove.
func (mr *MockWebServerConfigStoreMockRecorder) Remove(ctx, opts, ofp, pos any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Remove", reflect.TypeOf((*MockWebServerConfigStore)(nil).Remove), ctx, opts, ofp, pos)
}

// SearchContextPositions mocks base method.
func (m *MockWebServerConfigStore) SearchContextPositions(ctx context.Context, opts v10.WebServerOptions, ofp utils.ConfigFingerprints, kwmeta v10.SearchKeywordsMeta) ([]v10.ConfigContextPos, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchContextPositions", ctx, opts, ofp, kwmeta)
	ret0, _ := ret[0].([]v10.ConfigContextPos)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchContextPositions indicates an expected call of SearchContextPositions.
func (mr *MockWebServerConfigStoreMockRecorder) SearchContextPositions(ctx, opts, ofp, kwmeta any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchContextPositions", reflect.TypeOf((*MockWebServerConfigStore)(nil).SearchContextPositions), ctx, opts, ofp, kwmeta)
}
