// Code generated by MockGen. DO NOT EDIT.
// Source: web_server_config.go
//
// Generated by this command:
//
//	mockgen -source=web_server_config.go -destination=generics_mock_web_server_config.go -package=v1 gin-vue-admin/internal/hmdr_api/store/v1 WebServerConfigStore
//

// Package v1 is a generated GoMock package.
package v1

import (
	context "context"
	v1 "gin-vue-admin/api/heimdallr_api/v1"
	v10 "gin-vue-admin/internal/pkg/meta/v1"
	reflect "reflect"

	configuration "github.com/ClessLi/bifrost/pkg/resolv/V3/nginx/configuration"
	gomock "go.uber.org/mock/gomock"
)

// MockWebServerConfigStore is a mock of WebServerConfigStore interface.
type MockWebServerConfigStore struct {
	ctrl     *gomock.Controller
	recorder *MockWebServerConfigStoreMockRecorder
}

// MockWebServerConfigStoreMockRecorder is the mock recorder for MockWebServerConfigStore.
type MockWebServerConfigStoreMockRecorder struct {
	mock *MockWebServerConfigStore
}

// NewMockWebServerConfigStore creates a new mock instance.
func NewMockWebServerConfigStore(ctrl *gomock.Controller) *MockWebServerConfigStore {
	mock := &MockWebServerConfigStore{ctrl: ctrl}
	mock.recorder = &MockWebServerConfigStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWebServerConfigStore) EXPECT() *MockWebServerConfigStoreMockRecorder {
	return m.recorder
}

// GetConfig mocks base method.
func (m *MockWebServerConfigStore) GetConfig(ctx context.Context, opts v10.WebServerOptions) (configuration.NginxConfig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConfig", ctx, opts)
	ret0, _ := ret[0].(configuration.NginxConfig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetConfig indicates an expected call of GetConfig.
func (mr *MockWebServerConfigStoreMockRecorder) GetConfig(ctx, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConfig", reflect.TypeOf((*MockWebServerConfigStore)(nil).GetConfig), ctx, opts)
}

// GetOptions mocks base method.
func (m *MockWebServerConfigStore) GetOptions(ctx context.Context) ([]v1.BifrostGroupMeta, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOptions", ctx)
	ret0, _ := ret[0].([]v1.BifrostGroupMeta)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOptions indicates an expected call of GetOptions.
func (mr *MockWebServerConfigStoreMockRecorder) GetOptions(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOptions", reflect.TypeOf((*MockWebServerConfigStore)(nil).GetOptions), ctx)
}

// InsertWithClone mocks base method.
func (m *MockWebServerConfigStore) InsertWithClone(ctx context.Context, opts v10.WebServerOptions, ctxmeta v10.TargetConfigContextOptions[v10.CloneConfigContextMeta]) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertWithClone", ctx, opts, ctxmeta)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertWithClone indicates an expected call of InsertWithClone.
func (mr *MockWebServerConfigStoreMockRecorder) InsertWithClone(ctx, opts, ctxmeta any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertWithClone", reflect.TypeOf((*MockWebServerConfigStore)(nil).InsertWithClone), ctx, opts, ctxmeta)
}

// InsertWithNew mocks base method.
func (m *MockWebServerConfigStore) InsertWithNew(ctx context.Context, opts v10.WebServerOptions, ctxmeta v10.TargetConfigContextOptions[v10.NewConfigContextMeta]) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertWithNew", ctx, opts, ctxmeta)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertWithNew indicates an expected call of InsertWithNew.
func (mr *MockWebServerConfigStoreMockRecorder) InsertWithNew(ctx, opts, ctxmeta any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertWithNew", reflect.TypeOf((*MockWebServerConfigStore)(nil).InsertWithNew), ctx, opts, ctxmeta)
}

// ModifyWithClone mocks base method.
func (m *MockWebServerConfigStore) ModifyWithClone(ctx context.Context, opts v10.WebServerOptions, ctxmeta v10.TargetConfigContextOptions[v10.CloneConfigContextMeta]) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ModifyWithClone", ctx, opts, ctxmeta)
	ret0, _ := ret[0].(error)
	return ret0
}

// ModifyWithClone indicates an expected call of ModifyWithClone.
func (mr *MockWebServerConfigStoreMockRecorder) ModifyWithClone(ctx, opts, ctxmeta any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ModifyWithClone", reflect.TypeOf((*MockWebServerConfigStore)(nil).ModifyWithClone), ctx, opts, ctxmeta)
}

// ModifyWithNew mocks base method.
func (m *MockWebServerConfigStore) ModifyWithNew(ctx context.Context, opts v10.WebServerOptions, ctxmeta v10.TargetConfigContextOptions[v10.NewConfigContextMeta]) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ModifyWithNew", ctx, opts, ctxmeta)
	ret0, _ := ret[0].(error)
	return ret0
}

// ModifyWithNew indicates an expected call of ModifyWithNew.
func (mr *MockWebServerConfigStoreMockRecorder) ModifyWithNew(ctx, opts, ctxmeta any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ModifyWithNew", reflect.TypeOf((*MockWebServerConfigStore)(nil).ModifyWithNew), ctx, opts, ctxmeta)
}

// Move mocks base method.
func (m *MockWebServerConfigStore) Move(ctx context.Context, opts v10.WebServerOptions, ctxmeta v10.TargetConfigContextOptions[v10.CloneConfigContextMeta]) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Move", ctx, opts, ctxmeta)
	ret0, _ := ret[0].(error)
	return ret0
}

// Move indicates an expected call of Move.
func (mr *MockWebServerConfigStoreMockRecorder) Move(ctx, opts, ctxmeta any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Move", reflect.TypeOf((*MockWebServerConfigStore)(nil).Move), ctx, opts, ctxmeta)
}

// Remove mocks base method.
func (m *MockWebServerConfigStore) Remove(ctx context.Context, opts v10.WebServerOptions, pos v10.ConfigContextPos) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Remove", ctx, opts, pos)
	ret0, _ := ret[0].(error)
	return ret0
}

// Remove indicates an expected call of Remove.
func (mr *MockWebServerConfigStoreMockRecorder) Remove(ctx, opts, pos any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Remove", reflect.TypeOf((*MockWebServerConfigStore)(nil).Remove), ctx, opts, pos)
}
