// Code generated by MockGen. DO NOT EDIT.
// Source: gin-vue-admin/internal/hmdr_api/store/v1 (interfaces: Factory,AgentInfoStore,GroupStore,HostStore,WebServerLogWatcherStore,WebServerStatisticsStore)
//
// Generated by this command:
//
//	mockgen -self_package=gin-vue-admin/internal/hmdr_api/store/v1 -destination=mock_store.go -package=v1 gin-vue-admin/internal/hmdr_api/store/v1 Factory,AgentInfoStore,GroupStore,HostStore,WebServerLogWatcherStore,WebServerStatisticsStore
//

// Package v1 is a generated GoMock package.
package v1

import (
	context "context"
	v1 "gin-vue-admin/api/heimdallr_api/v1"
	v11 "gin-vue-admin/internal/pkg/meta/v1"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockFactory is a mock of Factory interface.
type MockFactory struct {
	ctrl     *gomock.Controller
	recorder *MockFactoryMockRecorder
}

// MockFactoryMockRecorder is the mock recorder for MockFactory.
type MockFactoryMockRecorder struct {
	mock *MockFactory
}

// NewMockFactory creates a new mock instance.
func NewMockFactory(ctrl *gomock.Controller) *MockFactory {
	mock := &MockFactory{ctrl: ctrl}
	mock.recorder = &MockFactoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFactory) EXPECT() *MockFactoryMockRecorder {
	return m.recorder
}

// AgentInfos mocks base method.
func (m *MockFactory) AgentInfos() AgentInfoStore {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AgentInfos")
	ret0, _ := ret[0].(AgentInfoStore)
	return ret0
}

// AgentInfos indicates an expected call of AgentInfos.
func (mr *MockFactoryMockRecorder) AgentInfos() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AgentInfos", reflect.TypeOf((*MockFactory)(nil).AgentInfos))
}

// Close mocks base method.
func (m *MockFactory) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockFactoryMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockFactory)(nil).Close))
}

// Groups mocks base method.
func (m *MockFactory) Groups() GroupStore {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Groups")
	ret0, _ := ret[0].(GroupStore)
	return ret0
}

// Groups indicates an expected call of Groups.
func (mr *MockFactoryMockRecorder) Groups() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Groups", reflect.TypeOf((*MockFactory)(nil).Groups))
}

// Hosts mocks base method.
func (m *MockFactory) Hosts() HostStore {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Hosts")
	ret0, _ := ret[0].(HostStore)
	return ret0
}

// Hosts indicates an expected call of Hosts.
func (mr *MockFactoryMockRecorder) Hosts() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Hosts", reflect.TypeOf((*MockFactory)(nil).Hosts))
}

// WebServerConfigs mocks base method.
func (m *MockFactory) WebServerConfigs() WebServerConfigStore {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WebServerConfigs")
	ret0, _ := ret[0].(WebServerConfigStore)
	return ret0
}

// WebServerConfigs indicates an expected call of WebServerConfigs.
func (mr *MockFactoryMockRecorder) WebServerConfigs() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WebServerConfigs", reflect.TypeOf((*MockFactory)(nil).WebServerConfigs))
}

// WebServerLogWatchers mocks base method.
func (m *MockFactory) WebServerLogWatchers() WebServerLogWatcherStore {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WebServerLogWatchers")
	ret0, _ := ret[0].(WebServerLogWatcherStore)
	return ret0
}

// WebServerLogWatchers indicates an expected call of WebServerLogWatchers.
func (mr *MockFactoryMockRecorder) WebServerLogWatchers() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WebServerLogWatchers", reflect.TypeOf((*MockFactory)(nil).WebServerLogWatchers))
}

// WebServerStatistics mocks base method.
func (m *MockFactory) WebServerStatistics() WebServerStatisticsStore {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WebServerStatistics")
	ret0, _ := ret[0].(WebServerStatisticsStore)
	return ret0
}

// WebServerStatistics indicates an expected call of WebServerStatistics.
func (mr *MockFactoryMockRecorder) WebServerStatistics() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WebServerStatistics", reflect.TypeOf((*MockFactory)(nil).WebServerStatistics))
}

// MockAgentInfoStore is a mock of AgentInfoStore interface.
type MockAgentInfoStore struct {
	ctrl     *gomock.Controller
	recorder *MockAgentInfoStoreMockRecorder
}

// MockAgentInfoStoreMockRecorder is the mock recorder for MockAgentInfoStore.
type MockAgentInfoStoreMockRecorder struct {
	mock *MockAgentInfoStore
}

// NewMockAgentInfoStore creates a new mock instance.
func NewMockAgentInfoStore(ctrl *gomock.Controller) *MockAgentInfoStore {
	mock := &MockAgentInfoStore{ctrl: ctrl}
	mock.recorder = &MockAgentInfoStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAgentInfoStore) EXPECT() *MockAgentInfoStoreMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockAgentInfoStore) Get(arg0 context.Context) ([]v1.GroupInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0)
	ret0, _ := ret[0].([]v1.GroupInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockAgentInfoStoreMockRecorder) Get(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockAgentInfoStore)(nil).Get), arg0)
}

// SyncAgentInfos mocks base method.
func (m *MockAgentInfoStore) SyncAgentInfos() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SyncAgentInfos")
}

// SyncAgentInfos indicates an expected call of SyncAgentInfos.
func (mr *MockAgentInfoStoreMockRecorder) SyncAgentInfos() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SyncAgentInfos", reflect.TypeOf((*MockAgentInfoStore)(nil).SyncAgentInfos))
}

// MockGroupStore is a mock of GroupStore interface.
type MockGroupStore struct {
	ctrl     *gomock.Controller
	recorder *MockGroupStoreMockRecorder
}

// MockGroupStoreMockRecorder is the mock recorder for MockGroupStore.
type MockGroupStoreMockRecorder struct {
	mock *MockGroupStore
}

// NewMockGroupStore creates a new mock instance.
func NewMockGroupStore(ctrl *gomock.Controller) *MockGroupStore {
	mock := &MockGroupStore{ctrl: ctrl}
	mock.recorder = &MockGroupStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGroupStore) EXPECT() *MockGroupStoreMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockGroupStore) Create(arg0 context.Context, arg1 v1.Group) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockGroupStoreMockRecorder) Create(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockGroupStore)(nil).Create), arg0, arg1)
}

// Delete mocks base method.
func (m *MockGroupStore) Delete(arg0 context.Context, arg1 uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockGroupStoreMockRecorder) Delete(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockGroupStore)(nil).Delete), arg0, arg1)
}

// DeleteCollections mocks base method.
func (m *MockGroupStore) DeleteCollections(arg0 context.Context, arg1 v11.IDsOptions) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCollections", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteCollections indicates an expected call of DeleteCollections.
func (mr *MockGroupStoreMockRecorder) DeleteCollections(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCollections", reflect.TypeOf((*MockGroupStore)(nil).DeleteCollections), arg0, arg1)
}

// Get mocks base method.
func (m *MockGroupStore) Get(arg0 context.Context, arg1 uint) (v1.Group, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0, arg1)
	ret0, _ := ret[0].(v1.Group)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockGroupStoreMockRecorder) Get(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockGroupStore)(nil).Get), arg0, arg1)
}

// List mocks base method.
func (m *MockGroupStore) List(arg0 context.Context, arg1 v11.ListOptions) (v1.GroupList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", arg0, arg1)
	ret0, _ := ret[0].(v1.GroupList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockGroupStoreMockRecorder) List(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockGroupStore)(nil).List), arg0, arg1)
}

// Update mocks base method.
func (m *MockGroupStore) Update(arg0 context.Context, arg1 v1.Group) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockGroupStoreMockRecorder) Update(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockGroupStore)(nil).Update), arg0, arg1)
}

// MockHostStore is a mock of HostStore interface.
type MockHostStore struct {
	ctrl     *gomock.Controller
	recorder *MockHostStoreMockRecorder
}

// MockHostStoreMockRecorder is the mock recorder for MockHostStore.
type MockHostStoreMockRecorder struct {
	mock *MockHostStore
}

// NewMockHostStore creates a new mock instance.
func NewMockHostStore(ctrl *gomock.Controller) *MockHostStore {
	mock := &MockHostStore{ctrl: ctrl}
	mock.recorder = &MockHostStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHostStore) EXPECT() *MockHostStoreMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockHostStore) Create(arg0 context.Context, arg1 v1.Host) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockHostStoreMockRecorder) Create(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockHostStore)(nil).Create), arg0, arg1)
}

// Delete mocks base method.
func (m *MockHostStore) Delete(arg0 context.Context, arg1 uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockHostStoreMockRecorder) Delete(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockHostStore)(nil).Delete), arg0, arg1)
}

// DeleteCollection mocks base method.
func (m *MockHostStore) DeleteCollection(arg0 context.Context, arg1 v11.IDsOptions) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCollection", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteCollection indicates an expected call of DeleteCollection.
func (mr *MockHostStoreMockRecorder) DeleteCollection(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCollection", reflect.TypeOf((*MockHostStore)(nil).DeleteCollection), arg0, arg1)
}

// Get mocks base method.
func (m *MockHostStore) Get(arg0 context.Context, arg1 uint) (v1.Host, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0, arg1)
	ret0, _ := ret[0].(v1.Host)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockHostStoreMockRecorder) Get(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockHostStore)(nil).Get), arg0, arg1)
}

// List mocks base method.
func (m *MockHostStore) List(arg0 context.Context, arg1 v11.ListOptions) (v1.HostList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", arg0, arg1)
	ret0, _ := ret[0].(v1.HostList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockHostStoreMockRecorder) List(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockHostStore)(nil).List), arg0, arg1)
}

// Update mocks base method.
func (m *MockHostStore) Update(arg0 context.Context, arg1 v1.Host) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockHostStoreMockRecorder) Update(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockHostStore)(nil).Update), arg0, arg1)
}

// MockWebServerLogWatcherStore is a mock of WebServerLogWatcherStore interface.
type MockWebServerLogWatcherStore struct {
	ctrl     *gomock.Controller
	recorder *MockWebServerLogWatcherStoreMockRecorder
}

// MockWebServerLogWatcherStoreMockRecorder is the mock recorder for MockWebServerLogWatcherStore.
type MockWebServerLogWatcherStoreMockRecorder struct {
	mock *MockWebServerLogWatcherStore
}

// NewMockWebServerLogWatcherStore creates a new mock instance.
func NewMockWebServerLogWatcherStore(ctrl *gomock.Controller) *MockWebServerLogWatcherStore {
	mock := &MockWebServerLogWatcherStore{ctrl: ctrl}
	mock.recorder = &MockWebServerLogWatcherStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWebServerLogWatcherStore) EXPECT() *MockWebServerLogWatcherStoreMockRecorder {
	return m.recorder
}

// Watch mocks base method.
func (m *MockWebServerLogWatcherStore) Watch(arg0 context.Context, arg1 v11.WebServerLogOptions) (<-chan []byte, context.CancelFunc, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Watch", arg0, arg1)
	ret0, _ := ret[0].(<-chan []byte)
	ret1, _ := ret[1].(context.CancelFunc)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Watch indicates an expected call of Watch.
func (mr *MockWebServerLogWatcherStoreMockRecorder) Watch(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Watch", reflect.TypeOf((*MockWebServerLogWatcherStore)(nil).Watch), arg0, arg1)
}

// MockWebServerStatisticsStore is a mock of WebServerStatisticsStore interface.
type MockWebServerStatisticsStore struct {
	ctrl     *gomock.Controller
	recorder *MockWebServerStatisticsStoreMockRecorder
}

// MockWebServerStatisticsStoreMockRecorder is the mock recorder for MockWebServerStatisticsStore.
type MockWebServerStatisticsStoreMockRecorder struct {
	mock *MockWebServerStatisticsStore
}

// NewMockWebServerStatisticsStore creates a new mock instance.
func NewMockWebServerStatisticsStore(ctrl *gomock.Controller) *MockWebServerStatisticsStore {
	mock := &MockWebServerStatisticsStore{ctrl: ctrl}
	mock.recorder = &MockWebServerStatisticsStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWebServerStatisticsStore) EXPECT() *MockWebServerStatisticsStoreMockRecorder {
	return m.recorder
}

// GetProxyServiceInfo mocks base method.
func (m *MockWebServerStatisticsStore) GetProxyServiceInfo(arg0 context.Context, arg1 v11.WebServerOptions) ([]v1.ProxyServiceInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProxyServiceInfo", arg0, arg1)
	ret0, _ := ret[0].([]v1.ProxyServiceInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProxyServiceInfo indicates an expected call of GetProxyServiceInfo.
func (mr *MockWebServerStatisticsStoreMockRecorder) GetProxyServiceInfo(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProxyServiceInfo", reflect.TypeOf((*MockWebServerStatisticsStore)(nil).GetProxyServiceInfo), arg0, arg1)
}
