// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/tanganyu1114/heimdallr-reborn/server/pkg/client/v1/transport (interfaces: Factory,SysUserTransport,AgentInfoTransport,GroupTransport,HostTransport,WebServerConfigTransport,WebServerBinCMDTransport,WebServerStatisticsTransport)
//
// Generated by this command:
//
//	mockgen -self_package=github.com/tanganyu1114/heimdallr-reborn/server/pkg/client/v1/transport -destination=mock_transport.go -package=transport github.com/tanganyu1114/heimdallr-reborn/server/pkg/client/v1/transport Factory,SysUserTransport,AgentInfoTransport,GroupTransport,HostTransport,WebServerConfigTransport,WebServerBinCMDTransport,WebServerStatisticsTransport
//

// Package transport is a generated GoMock package.
package transport

import (
	reflect "reflect"

	v1 "github.com/ClessLi/component-base/pkg/client-sdk/http/v1"
	v10 "github.com/tanganyu1114/heimdallr-reborn/server/api/heimdallr_api/v1"
	v11 "github.com/tanganyu1114/heimdallr-reborn/server/internal/pkg/meta/v1"
	request "github.com/tanganyu1114/heimdallr-reborn/server/model/request"
	response "github.com/tanganyu1114/heimdallr-reborn/server/model/response"
	model "github.com/tanganyu1114/heimdallr-reborn/server/pkg/client/v1/model"
	gomock "go.uber.org/mock/gomock"
)

// MockFactory is a mock of Factory interface.
type MockFactory struct {
	ctrl     *gomock.Controller
	recorder *MockFactoryMockRecorder
	isgomock struct{}
}

// MockFactoryMockRecorder is the mock recorder for MockFactory.
type MockFactoryMockRecorder struct {
	mock *MockFactory
}

// NewMockFactory creates a new mock instance.
func NewMockFactory(ctrl *gomock.Controller) *MockFactory {
	mock := &MockFactory{ctrl: ctrl}
	mock.recorder = &MockFactoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFactory) EXPECT() *MockFactoryMockRecorder {
	return m.recorder
}

// AgentInfos mocks base method.
func (m *MockFactory) AgentInfos() AgentInfoTransport {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AgentInfos")
	ret0, _ := ret[0].(AgentInfoTransport)
	return ret0
}

// AgentInfos indicates an expected call of AgentInfos.
func (mr *MockFactoryMockRecorder) AgentInfos() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AgentInfos", reflect.TypeOf((*MockFactory)(nil).AgentInfos))
}

// Groups mocks base method.
func (m *MockFactory) Groups() GroupTransport {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Groups")
	ret0, _ := ret[0].(GroupTransport)
	return ret0
}

// Groups indicates an expected call of Groups.
func (mr *MockFactoryMockRecorder) Groups() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Groups", reflect.TypeOf((*MockFactory)(nil).Groups))
}

// Hosts mocks base method.
func (m *MockFactory) Hosts() HostTransport {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Hosts")
	ret0, _ := ret[0].(HostTransport)
	return ret0
}

// Hosts indicates an expected call of Hosts.
func (mr *MockFactoryMockRecorder) Hosts() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Hosts", reflect.TypeOf((*MockFactory)(nil).Hosts))
}

// SysUsers mocks base method.
func (m *MockFactory) SysUsers() SysUserTransport {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SysUsers")
	ret0, _ := ret[0].(SysUserTransport)
	return ret0
}

// SysUsers indicates an expected call of SysUsers.
func (mr *MockFactoryMockRecorder) SysUsers() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SysUsers", reflect.TypeOf((*MockFactory)(nil).SysUsers))
}

// WebServerBinCMDs mocks base method.
func (m *MockFactory) WebServerBinCMDs() WebServerBinCMDTransport {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WebServerBinCMDs")
	ret0, _ := ret[0].(WebServerBinCMDTransport)
	return ret0
}

// WebServerBinCMDs indicates an expected call of WebServerBinCMDs.
func (mr *MockFactoryMockRecorder) WebServerBinCMDs() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WebServerBinCMDs", reflect.TypeOf((*MockFactory)(nil).WebServerBinCMDs))
}

// WebServerConfigs mocks base method.
func (m *MockFactory) WebServerConfigs() WebServerConfigTransport {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WebServerConfigs")
	ret0, _ := ret[0].(WebServerConfigTransport)
	return ret0
}

// WebServerConfigs indicates an expected call of WebServerConfigs.
func (mr *MockFactoryMockRecorder) WebServerConfigs() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WebServerConfigs", reflect.TypeOf((*MockFactory)(nil).WebServerConfigs))
}

// WebServerStatistics mocks base method.
func (m *MockFactory) WebServerStatistics() WebServerStatisticsTransport {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WebServerStatistics")
	ret0, _ := ret[0].(WebServerStatisticsTransport)
	return ret0
}

// WebServerStatistics indicates an expected call of WebServerStatistics.
func (mr *MockFactoryMockRecorder) WebServerStatistics() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WebServerStatistics", reflect.TypeOf((*MockFactory)(nil).WebServerStatistics))
}

// MockSysUserTransport is a mock of SysUserTransport interface.
type MockSysUserTransport struct {
	ctrl     *gomock.Controller
	recorder *MockSysUserTransportMockRecorder
	isgomock struct{}
}

// MockSysUserTransportMockRecorder is the mock recorder for MockSysUserTransport.
type MockSysUserTransportMockRecorder struct {
	mock *MockSysUserTransport
}

// NewMockSysUserTransport creates a new mock instance.
func NewMockSysUserTransport(ctrl *gomock.Controller) *MockSysUserTransport {
	mock := &MockSysUserTransport{ctrl: ctrl}
	mock.recorder = &MockSysUserTransportMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSysUserTransport) EXPECT() *MockSysUserTransportMockRecorder {
	return m.recorder
}

// GetSDKChallenge mocks base method.
func (m *MockSysUserTransport) GetSDKChallenge() v1.ClientBuilder[*request.SDKChallengeRequest, model.ResponseBody[*response.SDKChallengeResponse]] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSDKChallenge")
	ret0, _ := ret[0].(v1.ClientBuilder[*request.SDKChallengeRequest, model.ResponseBody[*response.SDKChallengeResponse]])
	return ret0
}

// GetSDKChallenge indicates an expected call of GetSDKChallenge.
func (mr *MockSysUserTransportMockRecorder) GetSDKChallenge() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSDKChallenge", reflect.TypeOf((*MockSysUserTransport)(nil).GetSDKChallenge))
}

// SDKLogin mocks base method.
func (m *MockSysUserTransport) SDKLogin() v1.ClientBuilder[*request.EncryptedLoginRequest, model.ResponseBody[*response.LoginResponse]] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SDKLogin")
	ret0, _ := ret[0].(v1.ClientBuilder[*request.EncryptedLoginRequest, model.ResponseBody[*response.LoginResponse]])
	return ret0
}

// SDKLogin indicates an expected call of SDKLogin.
func (mr *MockSysUserTransportMockRecorder) SDKLogin() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SDKLogin", reflect.TypeOf((*MockSysUserTransport)(nil).SDKLogin))
}

// MockAgentInfoTransport is a mock of AgentInfoTransport interface.
type MockAgentInfoTransport struct {
	ctrl     *gomock.Controller
	recorder *MockAgentInfoTransportMockRecorder
	isgomock struct{}
}

// MockAgentInfoTransportMockRecorder is the mock recorder for MockAgentInfoTransport.
type MockAgentInfoTransportMockRecorder struct {
	mock *MockAgentInfoTransport
}

// NewMockAgentInfoTransport creates a new mock instance.
func NewMockAgentInfoTransport(ctrl *gomock.Controller) *MockAgentInfoTransport {
	mock := &MockAgentInfoTransport{ctrl: ctrl}
	mock.recorder = &MockAgentInfoTransportMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAgentInfoTransport) EXPECT() *MockAgentInfoTransportMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockAgentInfoTransport) Get() v1.ClientBuilder[v1.NilBody, model.ResponseBody[[]v10.GroupInfo]] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get")
	ret0, _ := ret[0].(v1.ClientBuilder[v1.NilBody, model.ResponseBody[[]v10.GroupInfo]])
	return ret0
}

// Get indicates an expected call of Get.
func (mr *MockAgentInfoTransportMockRecorder) Get() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockAgentInfoTransport)(nil).Get))
}

// MockGroupTransport is a mock of GroupTransport interface.
type MockGroupTransport struct {
	ctrl     *gomock.Controller
	recorder *MockGroupTransportMockRecorder
	isgomock struct{}
}

// MockGroupTransportMockRecorder is the mock recorder for MockGroupTransport.
type MockGroupTransportMockRecorder struct {
	mock *MockGroupTransport
}

// NewMockGroupTransport creates a new mock instance.
func NewMockGroupTransport(ctrl *gomock.Controller) *MockGroupTransport {
	mock := &MockGroupTransport{ctrl: ctrl}
	mock.recorder = &MockGroupTransportMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGroupTransport) EXPECT() *MockGroupTransportMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockGroupTransport) Get() v1.ClientBuilder[v11.IDOptions, model.ResponseBody[*v10.Group]] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get")
	ret0, _ := ret[0].(v1.ClientBuilder[v11.IDOptions, model.ResponseBody[*v10.Group]])
	return ret0
}

// Get indicates an expected call of Get.
func (mr *MockGroupTransportMockRecorder) Get() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockGroupTransport)(nil).Get))
}

// List mocks base method.
func (m *MockGroupTransport) List() v1.ClientBuilder[v11.ListOptions, model.ResponseBody[*v10.GroupList]] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List")
	ret0, _ := ret[0].(v1.ClientBuilder[v11.ListOptions, model.ResponseBody[*v10.GroupList]])
	return ret0
}

// List indicates an expected call of List.
func (mr *MockGroupTransportMockRecorder) List() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockGroupTransport)(nil).List))
}

// MockHostTransport is a mock of HostTransport interface.
type MockHostTransport struct {
	ctrl     *gomock.Controller
	recorder *MockHostTransportMockRecorder
	isgomock struct{}
}

// MockHostTransportMockRecorder is the mock recorder for MockHostTransport.
type MockHostTransportMockRecorder struct {
	mock *MockHostTransport
}

// NewMockHostTransport creates a new mock instance.
func NewMockHostTransport(ctrl *gomock.Controller) *MockHostTransport {
	mock := &MockHostTransport{ctrl: ctrl}
	mock.recorder = &MockHostTransportMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHostTransport) EXPECT() *MockHostTransportMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockHostTransport) Get() v1.ClientBuilder[v11.IDOptions, model.ResponseBody[*v10.Host]] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get")
	ret0, _ := ret[0].(v1.ClientBuilder[v11.IDOptions, model.ResponseBody[*v10.Host]])
	return ret0
}

// Get indicates an expected call of Get.
func (mr *MockHostTransportMockRecorder) Get() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockHostTransport)(nil).Get))
}

// List mocks base method.
func (m *MockHostTransport) List() v1.ClientBuilder[v11.ListOptions, model.ResponseBody[*v10.HostList]] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List")
	ret0, _ := ret[0].(v1.ClientBuilder[v11.ListOptions, model.ResponseBody[*v10.HostList]])
	return ret0
}

// List indicates an expected call of List.
func (mr *MockHostTransportMockRecorder) List() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockHostTransport)(nil).List))
}

// MockWebServerConfigTransport is a mock of WebServerConfigTransport interface.
type MockWebServerConfigTransport struct {
	ctrl     *gomock.Controller
	recorder *MockWebServerConfigTransportMockRecorder
	isgomock struct{}
}

// MockWebServerConfigTransportMockRecorder is the mock recorder for MockWebServerConfigTransport.
type MockWebServerConfigTransportMockRecorder struct {
	mock *MockWebServerConfigTransport
}

// NewMockWebServerConfigTransport creates a new mock instance.
func NewMockWebServerConfigTransport(ctrl *gomock.Controller) *MockWebServerConfigTransport {
	mock := &MockWebServerConfigTransport{ctrl: ctrl}
	mock.recorder = &MockWebServerConfigTransportMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWebServerConfigTransport) EXPECT() *MockWebServerConfigTransportMockRecorder {
	return m.recorder
}

// ChangeContextEnabledState mocks base method.
func (m *MockWebServerConfigTransport) ChangeContextEnabledState() v1.ClientBuilder[v11.WebServerConfigContextUpdateOptions[v11.ConfigContextEnabledStateMeta], model.ResponseBody[v1.NilBody]] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChangeContextEnabledState")
	ret0, _ := ret[0].(v1.ClientBuilder[v11.WebServerConfigContextUpdateOptions[v11.ConfigContextEnabledStateMeta], model.ResponseBody[v1.NilBody]])
	return ret0
}

// ChangeContextEnabledState indicates an expected call of ChangeContextEnabledState.
func (mr *MockWebServerConfigTransportMockRecorder) ChangeContextEnabledState() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChangeContextEnabledState", reflect.TypeOf((*MockWebServerConfigTransport)(nil).ChangeContextEnabledState))
}

// GetConfig mocks base method.
func (m *MockWebServerConfigTransport) GetConfig() v1.ClientBuilder[v11.WebServerOptions, model.ResponseBody[*model.WebServerConfig]] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConfig")
	ret0, _ := ret[0].(v1.ClientBuilder[v11.WebServerOptions, model.ResponseBody[*model.WebServerConfig]])
	return ret0
}

// GetConfig indicates an expected call of GetConfig.
func (mr *MockWebServerConfigTransportMockRecorder) GetConfig() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConfig", reflect.TypeOf((*MockWebServerConfigTransport)(nil).GetConfig))
}

// GetConfigTextLines mocks base method.
func (m *MockWebServerConfigTransport) GetConfigTextLines() v1.ClientBuilder[v11.WebServerOptions, model.ResponseBody[string]] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConfigTextLines")
	ret0, _ := ret[0].(v1.ClientBuilder[v11.WebServerOptions, model.ResponseBody[string]])
	return ret0
}

// GetConfigTextLines indicates an expected call of GetConfigTextLines.
func (mr *MockWebServerConfigTransportMockRecorder) GetConfigTextLines() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConfigTextLines", reflect.TypeOf((*MockWebServerConfigTransport)(nil).GetConfigTextLines))
}

// GetContextTextLines mocks base method.
func (m *MockWebServerConfigTransport) GetContextTextLines() v1.ClientBuilder[v11.WebServerConfigTargetContextOptions, model.ResponseBody[string]] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetContextTextLines")
	ret0, _ := ret[0].(v1.ClientBuilder[v11.WebServerConfigTargetContextOptions, model.ResponseBody[string]])
	return ret0
}

// GetContextTextLines indicates an expected call of GetContextTextLines.
func (mr *MockWebServerConfigTransportMockRecorder) GetContextTextLines() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetContextTextLines", reflect.TypeOf((*MockWebServerConfigTransport)(nil).GetContextTextLines))
}

// GetIncludedConfigs mocks base method.
func (m *MockWebServerConfigTransport) GetIncludedConfigs() v1.ClientBuilder[v11.WebServerConfigTargetContextOptions, model.ResponseBody[[]string]] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIncludedConfigs")
	ret0, _ := ret[0].(v1.ClientBuilder[v11.WebServerConfigTargetContextOptions, model.ResponseBody[[]string]])
	return ret0
}

// GetIncludedConfigs indicates an expected call of GetIncludedConfigs.
func (mr *MockWebServerConfigTransportMockRecorder) GetIncludedConfigs() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIncludedConfigs", reflect.TypeOf((*MockWebServerConfigTransport)(nil).GetIncludedConfigs))
}

// GetOptions mocks base method.
func (m *MockWebServerConfigTransport) GetOptions() v1.ClientBuilder[v1.NilBody, model.ResponseBody[[]v10.BifrostGroupMeta]] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOptions")
	ret0, _ := ret[0].(v1.ClientBuilder[v1.NilBody, model.ResponseBody[[]v10.BifrostGroupMeta]])
	return ret0
}

// GetOptions indicates an expected call of GetOptions.
func (mr *MockWebServerConfigTransportMockRecorder) GetOptions() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOptions", reflect.TypeOf((*MockWebServerConfigTransport)(nil).GetOptions))
}

// InsertWithClone mocks base method.
func (m *MockWebServerConfigTransport) InsertWithClone() v1.ClientBuilder[v11.WebServerConfigContextUpdateOptions[v11.CloneConfigContextMeta], model.ResponseBody[v1.NilBody]] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertWithClone")
	ret0, _ := ret[0].(v1.ClientBuilder[v11.WebServerConfigContextUpdateOptions[v11.CloneConfigContextMeta], model.ResponseBody[v1.NilBody]])
	return ret0
}

// InsertWithClone indicates an expected call of InsertWithClone.
func (mr *MockWebServerConfigTransportMockRecorder) InsertWithClone() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertWithClone", reflect.TypeOf((*MockWebServerConfigTransport)(nil).InsertWithClone))
}

// InsertWithNew mocks base method.
func (m *MockWebServerConfigTransport) InsertWithNew() v1.ClientBuilder[v11.WebServerConfigContextUpdateOptions[v11.NewConfigContextMeta], model.ResponseBody[v1.NilBody]] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertWithNew")
	ret0, _ := ret[0].(v1.ClientBuilder[v11.WebServerConfigContextUpdateOptions[v11.NewConfigContextMeta], model.ResponseBody[v1.NilBody]])
	return ret0
}

// InsertWithNew indicates an expected call of InsertWithNew.
func (mr *MockWebServerConfigTransportMockRecorder) InsertWithNew() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertWithNew", reflect.TypeOf((*MockWebServerConfigTransport)(nil).InsertWithNew))
}

// ModifyContextValue mocks base method.
func (m *MockWebServerConfigTransport) ModifyContextValue() v1.ClientBuilder[v11.WebServerConfigContextUpdateOptions[v11.NewConfigContextMeta], model.ResponseBody[v1.NilBody]] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ModifyContextValue")
	ret0, _ := ret[0].(v1.ClientBuilder[v11.WebServerConfigContextUpdateOptions[v11.NewConfigContextMeta], model.ResponseBody[v1.NilBody]])
	return ret0
}

// ModifyContextValue indicates an expected call of ModifyContextValue.
func (mr *MockWebServerConfigTransportMockRecorder) ModifyContextValue() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ModifyContextValue", reflect.TypeOf((*MockWebServerConfigTransport)(nil).ModifyContextValue))
}

// ModifyWithClone mocks base method.
func (m *MockWebServerConfigTransport) ModifyWithClone() v1.ClientBuilder[v11.WebServerConfigContextUpdateOptions[v11.CloneConfigContextMeta], model.ResponseBody[v1.NilBody]] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ModifyWithClone")
	ret0, _ := ret[0].(v1.ClientBuilder[v11.WebServerConfigContextUpdateOptions[v11.CloneConfigContextMeta], model.ResponseBody[v1.NilBody]])
	return ret0
}

// ModifyWithClone indicates an expected call of ModifyWithClone.
func (mr *MockWebServerConfigTransportMockRecorder) ModifyWithClone() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ModifyWithClone", reflect.TypeOf((*MockWebServerConfigTransport)(nil).ModifyWithClone))
}

// ModifyWithNew mocks base method.
func (m *MockWebServerConfigTransport) ModifyWithNew() v1.ClientBuilder[v11.WebServerConfigContextUpdateOptions[v11.NewConfigContextMeta], model.ResponseBody[v1.NilBody]] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ModifyWithNew")
	ret0, _ := ret[0].(v1.ClientBuilder[v11.WebServerConfigContextUpdateOptions[v11.NewConfigContextMeta], model.ResponseBody[v1.NilBody]])
	return ret0
}

// ModifyWithNew indicates an expected call of ModifyWithNew.
func (mr *MockWebServerConfigTransportMockRecorder) ModifyWithNew() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ModifyWithNew", reflect.TypeOf((*MockWebServerConfigTransport)(nil).ModifyWithNew))
}

// Move mocks base method.
func (m *MockWebServerConfigTransport) Move() v1.ClientBuilder[v11.WebServerConfigContextUpdateOptions[v11.CloneConfigContextMeta], model.ResponseBody[v1.NilBody]] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Move")
	ret0, _ := ret[0].(v1.ClientBuilder[v11.WebServerConfigContextUpdateOptions[v11.CloneConfigContextMeta], model.ResponseBody[v1.NilBody]])
	return ret0
}

// Move indicates an expected call of Move.
func (mr *MockWebServerConfigTransportMockRecorder) Move() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Move", reflect.TypeOf((*MockWebServerConfigTransport)(nil).Move))
}

// Remove mocks base method.
func (m *MockWebServerConfigTransport) Remove() v1.ClientBuilder[v11.WebServerConfigTargetContextOptions, model.ResponseBody[v1.NilBody]] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Remove")
	ret0, _ := ret[0].(v1.ClientBuilder[v11.WebServerConfigTargetContextOptions, model.ResponseBody[v1.NilBody]])
	return ret0
}

// Remove indicates an expected call of Remove.
func (mr *MockWebServerConfigTransportMockRecorder) Remove() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Remove", reflect.TypeOf((*MockWebServerConfigTransport)(nil).Remove))
}

// SearchContextPositions mocks base method.
func (m *MockWebServerConfigTransport) SearchContextPositions() v1.ClientBuilder[v11.WebServerConfigContextPosSearchOptions, model.ResponseBody[[]v11.ConfigContextPos]] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchContextPositions")
	ret0, _ := ret[0].(v1.ClientBuilder[v11.WebServerConfigContextPosSearchOptions, model.ResponseBody[[]v11.ConfigContextPos]])
	return ret0
}

// SearchContextPositions indicates an expected call of SearchContextPositions.
func (mr *MockWebServerConfigTransportMockRecorder) SearchContextPositions() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchContextPositions", reflect.TypeOf((*MockWebServerConfigTransport)(nil).SearchContextPositions))
}

// UpdateConfig mocks base method.
func (m *MockWebServerConfigTransport) UpdateConfig() v1.ClientBuilder[*v11.WebServerConfigUpdateOptions, model.ResponseBody[v1.NilBody]] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateConfig")
	ret0, _ := ret[0].(v1.ClientBuilder[*v11.WebServerConfigUpdateOptions, model.ResponseBody[v1.NilBody]])
	return ret0
}

// UpdateConfig indicates an expected call of UpdateConfig.
func (mr *MockWebServerConfigTransportMockRecorder) UpdateConfig() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateConfig", reflect.TypeOf((*MockWebServerConfigTransport)(nil).UpdateConfig))
}

// MockWebServerBinCMDTransport is a mock of WebServerBinCMDTransport interface.
type MockWebServerBinCMDTransport struct {
	ctrl     *gomock.Controller
	recorder *MockWebServerBinCMDTransportMockRecorder
	isgomock struct{}
}

// MockWebServerBinCMDTransportMockRecorder is the mock recorder for MockWebServerBinCMDTransport.
type MockWebServerBinCMDTransportMockRecorder struct {
	mock *MockWebServerBinCMDTransport
}

// NewMockWebServerBinCMDTransport creates a new mock instance.
func NewMockWebServerBinCMDTransport(ctrl *gomock.Controller) *MockWebServerBinCMDTransport {
	mock := &MockWebServerBinCMDTransport{ctrl: ctrl}
	mock.recorder = &MockWebServerBinCMDTransportMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWebServerBinCMDTransport) EXPECT() *MockWebServerBinCMDTransportMockRecorder {
	return m.recorder
}

// Exec mocks base method.
func (m *MockWebServerBinCMDTransport) Exec() v1.ClientBuilder[v11.WebServerBinCMDExecRequest, model.ResponseBody[*v11.WebServerBinCMDExecResponse]] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Exec")
	ret0, _ := ret[0].(v1.ClientBuilder[v11.WebServerBinCMDExecRequest, model.ResponseBody[*v11.WebServerBinCMDExecResponse]])
	return ret0
}

// Exec indicates an expected call of Exec.
func (mr *MockWebServerBinCMDTransportMockRecorder) Exec() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exec", reflect.TypeOf((*MockWebServerBinCMDTransport)(nil).Exec))
}

// MockWebServerStatisticsTransport is a mock of WebServerStatisticsTransport interface.
type MockWebServerStatisticsTransport struct {
	ctrl     *gomock.Controller
	recorder *MockWebServerStatisticsTransportMockRecorder
	isgomock struct{}
}

// MockWebServerStatisticsTransportMockRecorder is the mock recorder for MockWebServerStatisticsTransport.
type MockWebServerStatisticsTransportMockRecorder struct {
	mock *MockWebServerStatisticsTransport
}

// NewMockWebServerStatisticsTransport creates a new mock instance.
func NewMockWebServerStatisticsTransport(ctrl *gomock.Controller) *MockWebServerStatisticsTransport {
	mock := &MockWebServerStatisticsTransport{ctrl: ctrl}
	mock.recorder = &MockWebServerStatisticsTransportMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWebServerStatisticsTransport) EXPECT() *MockWebServerStatisticsTransportMockRecorder {
	return m.recorder
}

// ConnectivityCheckOfProxyService mocks base method.
func (m *MockWebServerStatisticsTransport) ConnectivityCheckOfProxyService() v1.ClientBuilder[v11.ConnectivityCheckOfProxiedServersRequestOptions, model.ResponseBody[v10.ProxyServiceInfo]] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConnectivityCheckOfProxyService")
	ret0, _ := ret[0].(v1.ClientBuilder[v11.ConnectivityCheckOfProxiedServersRequestOptions, model.ResponseBody[v10.ProxyServiceInfo]])
	return ret0
}

// ConnectivityCheckOfProxyService indicates an expected call of ConnectivityCheckOfProxyService.
func (mr *MockWebServerStatisticsTransportMockRecorder) ConnectivityCheckOfProxyService() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConnectivityCheckOfProxyService", reflect.TypeOf((*MockWebServerStatisticsTransport)(nil).ConnectivityCheckOfProxyService))
}

// ExportProxyServiceInfoToExcel mocks base method.
func (m *MockWebServerStatisticsTransport) ExportProxyServiceInfoToExcel() v1.ClientBuilder[v11.WebServerOptions, model.ResponseBody[[]byte]] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExportProxyServiceInfoToExcel")
	ret0, _ := ret[0].(v1.ClientBuilder[v11.WebServerOptions, model.ResponseBody[[]byte]])
	return ret0
}

// ExportProxyServiceInfoToExcel indicates an expected call of ExportProxyServiceInfoToExcel.
func (mr *MockWebServerStatisticsTransportMockRecorder) ExportProxyServiceInfoToExcel() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExportProxyServiceInfoToExcel", reflect.TypeOf((*MockWebServerStatisticsTransport)(nil).ExportProxyServiceInfoToExcel))
}

// GetProxyServiceInfo mocks base method.
func (m *MockWebServerStatisticsTransport) GetProxyServiceInfo() v1.ClientBuilder[v11.WebServerOptions, model.ResponseBody[[]v10.ProxyServiceInfo]] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProxyServiceInfo")
	ret0, _ := ret[0].(v1.ClientBuilder[v11.WebServerOptions, model.ResponseBody[[]v10.ProxyServiceInfo]])
	return ret0
}

// GetProxyServiceInfo indicates an expected call of GetProxyServiceInfo.
func (mr *MockWebServerStatisticsTransportMockRecorder) GetProxyServiceInfo() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProxyServiceInfo", reflect.TypeOf((*MockWebServerStatisticsTransport)(nil).GetProxyServiceInfo))
}
