// Code generated by MockGen. DO NOT EDIT.
// Source: gin-vue-admin/pkg/client/v1/service (interfaces: Factory,AgentInfoService,GroupService,HostService,WebServerConfigService,WebServerBinCMDService,WebServerStatisticsService)
//
// Generated by this command:
//
//	mockgen -self_package=gin-vue-admin/pkg/client/v1/service -destination=mock_service.go -package=service gin-vue-admin/pkg/client/v1/service Factory,AgentInfoService,GroupService,HostService,WebServerConfigService,WebServerBinCMDService,WebServerStatisticsService
//

// Package service is a generated GoMock package.
package service

import (
	v1 "github.com/tanganyu1114/heimdallr-reborn/api/heimdallr_api/v1"
	v10 "github.com/tanganyu1114/heimdallr-reborn/internal/pkg/meta/v1"
	reflect "reflect"

	configuration "github.com/ClessLi/bifrost/pkg/resolv/V3/nginx/configuration"
	utils "github.com/ClessLi/bifrost/pkg/resolv/V3/nginx/configuration/utils"
	gomock "go.uber.org/mock/gomock"
)

// MockFactory is a mock of Factory interface.
type MockFactory struct {
	ctrl     *gomock.Controller
	recorder *MockFactoryMockRecorder
	isgomock struct{}
}

// MockFactoryMockRecorder is the mock recorder for MockFactory.
type MockFactoryMockRecorder struct {
	mock *MockFactory
}

// NewMockFactory creates a new mock instance.
func NewMockFactory(ctrl *gomock.Controller) *MockFactory {
	mock := &MockFactory{ctrl: ctrl}
	mock.recorder = &MockFactoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFactory) EXPECT() *MockFactoryMockRecorder {
	return m.recorder
}

// AgentInfos mocks base method.
func (m *MockFactory) AgentInfos() AgentInfoService {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AgentInfos")
	ret0, _ := ret[0].(AgentInfoService)
	return ret0
}

// AgentInfos indicates an expected call of AgentInfos.
func (mr *MockFactoryMockRecorder) AgentInfos() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AgentInfos", reflect.TypeOf((*MockFactory)(nil).AgentInfos))
}

// Groups mocks base method.
func (m *MockFactory) Groups() GroupService {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Groups")
	ret0, _ := ret[0].(GroupService)
	return ret0
}

// Groups indicates an expected call of Groups.
func (mr *MockFactoryMockRecorder) Groups() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Groups", reflect.TypeOf((*MockFactory)(nil).Groups))
}

// Hosts mocks base method.
func (m *MockFactory) Hosts() HostService {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Hosts")
	ret0, _ := ret[0].(HostService)
	return ret0
}

// Hosts indicates an expected call of Hosts.
func (mr *MockFactoryMockRecorder) Hosts() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Hosts", reflect.TypeOf((*MockFactory)(nil).Hosts))
}

// WebServerBinCMDs mocks base method.
func (m *MockFactory) WebServerBinCMDs() WebServerBinCMDService {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WebServerBinCMDs")
	ret0, _ := ret[0].(WebServerBinCMDService)
	return ret0
}

// WebServerBinCMDs indicates an expected call of WebServerBinCMDs.
func (mr *MockFactoryMockRecorder) WebServerBinCMDs() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WebServerBinCMDs", reflect.TypeOf((*MockFactory)(nil).WebServerBinCMDs))
}

// WebServerConfigs mocks base method.
func (m *MockFactory) WebServerConfigs() WebServerConfigService {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WebServerConfigs")
	ret0, _ := ret[0].(WebServerConfigService)
	return ret0
}

// WebServerConfigs indicates an expected call of WebServerConfigs.
func (mr *MockFactoryMockRecorder) WebServerConfigs() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WebServerConfigs", reflect.TypeOf((*MockFactory)(nil).WebServerConfigs))
}

// WebServerStatistics mocks base method.
func (m *MockFactory) WebServerStatistics() WebServerStatisticsService {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WebServerStatistics")
	ret0, _ := ret[0].(WebServerStatisticsService)
	return ret0
}

// WebServerStatistics indicates an expected call of WebServerStatistics.
func (mr *MockFactoryMockRecorder) WebServerStatistics() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WebServerStatistics", reflect.TypeOf((*MockFactory)(nil).WebServerStatistics))
}

// MockAgentInfoService is a mock of AgentInfoService interface.
type MockAgentInfoService struct {
	ctrl     *gomock.Controller
	recorder *MockAgentInfoServiceMockRecorder
	isgomock struct{}
}

// MockAgentInfoServiceMockRecorder is the mock recorder for MockAgentInfoService.
type MockAgentInfoServiceMockRecorder struct {
	mock *MockAgentInfoService
}

// NewMockAgentInfoService creates a new mock instance.
func NewMockAgentInfoService(ctrl *gomock.Controller) *MockAgentInfoService {
	mock := &MockAgentInfoService{ctrl: ctrl}
	mock.recorder = &MockAgentInfoServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAgentInfoService) EXPECT() *MockAgentInfoServiceMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockAgentInfoService) Get() ([]v1.GroupInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get")
	ret0, _ := ret[0].([]v1.GroupInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockAgentInfoServiceMockRecorder) Get() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockAgentInfoService)(nil).Get))
}

// MockGroupService is a mock of GroupService interface.
type MockGroupService struct {
	ctrl     *gomock.Controller
	recorder *MockGroupServiceMockRecorder
	isgomock struct{}
}

// MockGroupServiceMockRecorder is the mock recorder for MockGroupService.
type MockGroupServiceMockRecorder struct {
	mock *MockGroupService
}

// NewMockGroupService creates a new mock instance.
func NewMockGroupService(ctrl *gomock.Controller) *MockGroupService {
	mock := &MockGroupService{ctrl: ctrl}
	mock.recorder = &MockGroupServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGroupService) EXPECT() *MockGroupServiceMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockGroupService) Get(idOptions *v10.IDOptions) (*v1.Group, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", idOptions)
	ret0, _ := ret[0].(*v1.Group)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockGroupServiceMockRecorder) Get(idOptions any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockGroupService)(nil).Get), idOptions)
}

// List mocks base method.
func (m *MockGroupService) List(listOptions *v10.ListOptions) (*v1.GroupList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", listOptions)
	ret0, _ := ret[0].(*v1.GroupList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockGroupServiceMockRecorder) List(listOptions any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockGroupService)(nil).List), listOptions)
}

// MockHostService is a mock of HostService interface.
type MockHostService struct {
	ctrl     *gomock.Controller
	recorder *MockHostServiceMockRecorder
	isgomock struct{}
}

// MockHostServiceMockRecorder is the mock recorder for MockHostService.
type MockHostServiceMockRecorder struct {
	mock *MockHostService
}

// NewMockHostService creates a new mock instance.
func NewMockHostService(ctrl *gomock.Controller) *MockHostService {
	mock := &MockHostService{ctrl: ctrl}
	mock.recorder = &MockHostServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHostService) EXPECT() *MockHostServiceMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockHostService) Get(idOptions *v10.IDOptions) (*v1.Host, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", idOptions)
	ret0, _ := ret[0].(*v1.Host)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockHostServiceMockRecorder) Get(idOptions any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockHostService)(nil).Get), idOptions)
}

// List mocks base method.
func (m *MockHostService) List(listOptions *v10.ListOptions) (*v1.HostList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", listOptions)
	ret0, _ := ret[0].(*v1.HostList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockHostServiceMockRecorder) List(listOptions any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockHostService)(nil).List), listOptions)
}

// MockWebServerConfigService is a mock of WebServerConfigService interface.
type MockWebServerConfigService struct {
	ctrl     *gomock.Controller
	recorder *MockWebServerConfigServiceMockRecorder
	isgomock struct{}
}

// MockWebServerConfigServiceMockRecorder is the mock recorder for MockWebServerConfigService.
type MockWebServerConfigServiceMockRecorder struct {
	mock *MockWebServerConfigService
}

// NewMockWebServerConfigService creates a new mock instance.
func NewMockWebServerConfigService(ctrl *gomock.Controller) *MockWebServerConfigService {
	mock := &MockWebServerConfigService{ctrl: ctrl}
	mock.recorder = &MockWebServerConfigServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWebServerConfigService) EXPECT() *MockWebServerConfigServiceMockRecorder {
	return m.recorder
}

// ChangeContextEnabledState mocks base method.
func (m *MockWebServerConfigService) ChangeContextEnabledState(opts *v10.WebServerConfigContextUpdateOptions[v10.ConfigContextEnabledStateMeta]) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChangeContextEnabledState", opts)
	ret0, _ := ret[0].(error)
	return ret0
}

// ChangeContextEnabledState indicates an expected call of ChangeContextEnabledState.
func (mr *MockWebServerConfigServiceMockRecorder) ChangeContextEnabledState(opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChangeContextEnabledState", reflect.TypeOf((*MockWebServerConfigService)(nil).ChangeContextEnabledState), opts)
}

// GetConfig mocks base method.
func (m *MockWebServerConfigService) GetConfig(opts *v10.WebServerOptions) (configuration.NginxConfig, utils.ConfigFingerprints, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConfig", opts)
	ret0, _ := ret[0].(configuration.NginxConfig)
	ret1, _ := ret[1].(utils.ConfigFingerprints)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetConfig indicates an expected call of GetConfig.
func (mr *MockWebServerConfigServiceMockRecorder) GetConfig(opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConfig", reflect.TypeOf((*MockWebServerConfigService)(nil).GetConfig), opts)
}

// GetConfigTextLines mocks base method.
func (m *MockWebServerConfigService) GetConfigTextLines(opts *v10.WebServerOptions) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConfigTextLines", opts)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetConfigTextLines indicates an expected call of GetConfigTextLines.
func (mr *MockWebServerConfigServiceMockRecorder) GetConfigTextLines(opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConfigTextLines", reflect.TypeOf((*MockWebServerConfigService)(nil).GetConfigTextLines), opts)
}

// GetContextTextLines mocks base method.
func (m *MockWebServerConfigService) GetContextTextLines(opts *v10.WebServerConfigTargetContextOptions) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetContextTextLines", opts)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetContextTextLines indicates an expected call of GetContextTextLines.
func (mr *MockWebServerConfigServiceMockRecorder) GetContextTextLines(opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetContextTextLines", reflect.TypeOf((*MockWebServerConfigService)(nil).GetContextTextLines), opts)
}

// GetIncludedConfigs mocks base method.
func (m *MockWebServerConfigService) GetIncludedConfigs(opts *v10.WebServerConfigTargetContextOptions) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIncludedConfigs", opts)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetIncludedConfigs indicates an expected call of GetIncludedConfigs.
func (mr *MockWebServerConfigServiceMockRecorder) GetIncludedConfigs(opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIncludedConfigs", reflect.TypeOf((*MockWebServerConfigService)(nil).GetIncludedConfigs), opts)
}

// GetOptions mocks base method.
func (m *MockWebServerConfigService) GetOptions() ([]v1.BifrostGroupMeta, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOptions")
	ret0, _ := ret[0].([]v1.BifrostGroupMeta)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOptions indicates an expected call of GetOptions.
func (mr *MockWebServerConfigServiceMockRecorder) GetOptions() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOptions", reflect.TypeOf((*MockWebServerConfigService)(nil).GetOptions))
}

// InsertWithClone mocks base method.
func (m *MockWebServerConfigService) InsertWithClone(opts *v10.WebServerConfigContextUpdateOptions[v10.CloneConfigContextMeta]) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertWithClone", opts)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertWithClone indicates an expected call of InsertWithClone.
func (mr *MockWebServerConfigServiceMockRecorder) InsertWithClone(opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertWithClone", reflect.TypeOf((*MockWebServerConfigService)(nil).InsertWithClone), opts)
}

// InsertWithNew mocks base method.
func (m *MockWebServerConfigService) InsertWithNew(opts *v10.WebServerConfigContextUpdateOptions[v10.NewConfigContextMeta]) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertWithNew", opts)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertWithNew indicates an expected call of InsertWithNew.
func (mr *MockWebServerConfigServiceMockRecorder) InsertWithNew(opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertWithNew", reflect.TypeOf((*MockWebServerConfigService)(nil).InsertWithNew), opts)
}

// ModifyContextValue mocks base method.
func (m *MockWebServerConfigService) ModifyContextValue(opts *v10.WebServerConfigContextUpdateOptions[v10.NewConfigContextMeta]) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ModifyContextValue", opts)
	ret0, _ := ret[0].(error)
	return ret0
}

// ModifyContextValue indicates an expected call of ModifyContextValue.
func (mr *MockWebServerConfigServiceMockRecorder) ModifyContextValue(opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ModifyContextValue", reflect.TypeOf((*MockWebServerConfigService)(nil).ModifyContextValue), opts)
}

// ModifyWithClone mocks base method.
func (m *MockWebServerConfigService) ModifyWithClone(opts *v10.WebServerConfigContextUpdateOptions[v10.CloneConfigContextMeta]) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ModifyWithClone", opts)
	ret0, _ := ret[0].(error)
	return ret0
}

// ModifyWithClone indicates an expected call of ModifyWithClone.
func (mr *MockWebServerConfigServiceMockRecorder) ModifyWithClone(opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ModifyWithClone", reflect.TypeOf((*MockWebServerConfigService)(nil).ModifyWithClone), opts)
}

// ModifyWithNew mocks base method.
func (m *MockWebServerConfigService) ModifyWithNew(opts *v10.WebServerConfigContextUpdateOptions[v10.NewConfigContextMeta]) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ModifyWithNew", opts)
	ret0, _ := ret[0].(error)
	return ret0
}

// ModifyWithNew indicates an expected call of ModifyWithNew.
func (mr *MockWebServerConfigServiceMockRecorder) ModifyWithNew(opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ModifyWithNew", reflect.TypeOf((*MockWebServerConfigService)(nil).ModifyWithNew), opts)
}

// Move mocks base method.
func (m *MockWebServerConfigService) Move(opts *v10.WebServerConfigContextUpdateOptions[v10.CloneConfigContextMeta]) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Move", opts)
	ret0, _ := ret[0].(error)
	return ret0
}

// Move indicates an expected call of Move.
func (mr *MockWebServerConfigServiceMockRecorder) Move(opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Move", reflect.TypeOf((*MockWebServerConfigService)(nil).Move), opts)
}

// Remove mocks base method.
func (m *MockWebServerConfigService) Remove(opts *v10.WebServerConfigTargetContextOptions) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Remove", opts)
	ret0, _ := ret[0].(error)
	return ret0
}

// Remove indicates an expected call of Remove.
func (mr *MockWebServerConfigServiceMockRecorder) Remove(opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Remove", reflect.TypeOf((*MockWebServerConfigService)(nil).Remove), opts)
}

// SearchContextPositions mocks base method.
func (m *MockWebServerConfigService) SearchContextPositions(opts *v10.WebServerConfigContextPosSearchOptions) ([]v10.ConfigContextPos, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchContextPositions", opts)
	ret0, _ := ret[0].([]v10.ConfigContextPos)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchContextPositions indicates an expected call of SearchContextPositions.
func (mr *MockWebServerConfigServiceMockRecorder) SearchContextPositions(opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchContextPositions", reflect.TypeOf((*MockWebServerConfigService)(nil).SearchContextPositions), opts)
}

// UpdateConfig mocks base method.
func (m *MockWebServerConfigService) UpdateConfig(opts *v10.WebServerConfigUpdateOptions) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateConfig", opts)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateConfig indicates an expected call of UpdateConfig.
func (mr *MockWebServerConfigServiceMockRecorder) UpdateConfig(opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateConfig", reflect.TypeOf((*MockWebServerConfigService)(nil).UpdateConfig), opts)
}

// MockWebServerBinCMDService is a mock of WebServerBinCMDService interface.
type MockWebServerBinCMDService struct {
	ctrl     *gomock.Controller
	recorder *MockWebServerBinCMDServiceMockRecorder
	isgomock struct{}
}

// MockWebServerBinCMDServiceMockRecorder is the mock recorder for MockWebServerBinCMDService.
type MockWebServerBinCMDServiceMockRecorder struct {
	mock *MockWebServerBinCMDService
}

// NewMockWebServerBinCMDService creates a new mock instance.
func NewMockWebServerBinCMDService(ctrl *gomock.Controller) *MockWebServerBinCMDService {
	mock := &MockWebServerBinCMDService{ctrl: ctrl}
	mock.recorder = &MockWebServerBinCMDServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWebServerBinCMDService) EXPECT() *MockWebServerBinCMDServiceMockRecorder {
	return m.recorder
}

// Exec mocks base method.
func (m *MockWebServerBinCMDService) Exec(req *v10.WebServerBinCMDExecRequest) (*v10.WebServerBinCMDExecResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Exec", req)
	ret0, _ := ret[0].(*v10.WebServerBinCMDExecResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Exec indicates an expected call of Exec.
func (mr *MockWebServerBinCMDServiceMockRecorder) Exec(req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exec", reflect.TypeOf((*MockWebServerBinCMDService)(nil).Exec), req)
}

// MockWebServerStatisticsService is a mock of WebServerStatisticsService interface.
type MockWebServerStatisticsService struct {
	ctrl     *gomock.Controller
	recorder *MockWebServerStatisticsServiceMockRecorder
	isgomock struct{}
}

// MockWebServerStatisticsServiceMockRecorder is the mock recorder for MockWebServerStatisticsService.
type MockWebServerStatisticsServiceMockRecorder struct {
	mock *MockWebServerStatisticsService
}

// NewMockWebServerStatisticsService creates a new mock instance.
func NewMockWebServerStatisticsService(ctrl *gomock.Controller) *MockWebServerStatisticsService {
	mock := &MockWebServerStatisticsService{ctrl: ctrl}
	mock.recorder = &MockWebServerStatisticsServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWebServerStatisticsService) EXPECT() *MockWebServerStatisticsServiceMockRecorder {
	return m.recorder
}

// ConnectivityCheckOfProxyService mocks base method.
func (m *MockWebServerStatisticsService) ConnectivityCheckOfProxyService(opts *v10.ConnectivityCheckOfProxiedServersRequestOptions) (v1.ProxyServiceInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConnectivityCheckOfProxyService", opts)
	ret0, _ := ret[0].(v1.ProxyServiceInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ConnectivityCheckOfProxyService indicates an expected call of ConnectivityCheckOfProxyService.
func (mr *MockWebServerStatisticsServiceMockRecorder) ConnectivityCheckOfProxyService(opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConnectivityCheckOfProxyService", reflect.TypeOf((*MockWebServerStatisticsService)(nil).ConnectivityCheckOfProxyService), opts)
}

// ExportProxyServiceInfoToExcel mocks base method.
func (m *MockWebServerStatisticsService) ExportProxyServiceInfoToExcel(opts *v10.WebServerOptions) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExportProxyServiceInfoToExcel", opts)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExportProxyServiceInfoToExcel indicates an expected call of ExportProxyServiceInfoToExcel.
func (mr *MockWebServerStatisticsServiceMockRecorder) ExportProxyServiceInfoToExcel(opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExportProxyServiceInfoToExcel", reflect.TypeOf((*MockWebServerStatisticsService)(nil).ExportProxyServiceInfoToExcel), opts)
}

// GetProxyServiceInfo mocks base method.
func (m *MockWebServerStatisticsService) GetProxyServiceInfo(opts *v10.WebServerOptions) ([]v1.ProxyServiceInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProxyServiceInfo", opts)
	ret0, _ := ret[0].([]v1.ProxyServiceInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProxyServiceInfo indicates an expected call of GetProxyServiceInfo.
func (mr *MockWebServerStatisticsServiceMockRecorder) GetProxyServiceInfo(opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProxyServiceInfo", reflect.TypeOf((*MockWebServerStatisticsService)(nil).GetProxyServiceInfo), opts)
}
